/**
 * ============================================================
 * GUIDE LOADER — lazy runtime load of the per-language upkeep-guide catalogs
 * ============================================================
 *
 * The same bundle-en / serve-the-rest split the UI locales use (src/i18n/index.js),
 * applied to the ~2.4 MB of translated maintenance-guide text:
 *
 *   - English is BUNDLED (guide-translations.js) so it is ALWAYS sync-available as
 *     the universal fallback — renderers/maintenance.js `_localizedGuide` needs the
 *     English value on every miss.
 *   - Every other language is SERVED as /eufy_vacuum/frontend/guides/<lang>.json
 *     (generated by scripts/sync-guide-translations.py) and fetched ONCE at runtime
 *     into GUIDE_CATALOGS, so the translated text is no longer parsed as JavaScript
 *     on every card load.
 *
 * `_localizedGuide` reads GUIDE_CATALOGS synchronously via `guideCatalog(lang)`;
 * before a language's file arrives it falls back to English exactly as the bundled
 * object did, and the maintenance view re-renders when the file loads.
 *
 * Everything FAILS SOFT: any fetch/parse error leaves English (and any
 * already-loaded language) in place — a guide translation must never break render.
 * ============================================================
 */

import { GUIDE_TRANSLATIONS } from "./guide-translations.js";

/**
 * lang -> { family -> { component -> { steps[], notes[], clean_frequency, replace_frequency } } }.
 * Seeded with the bundled English base; other languages register at runtime.
 */
const GUIDE_CATALOGS = { en: (GUIDE_TRANSLATIONS && GUIDE_TRANSLATIONS.en) || {} };

/**
 * Build-injected cache-bust token for the served guide catalogs (esbuild
 * --define __GUIDE_VER__, keyed to the guide files' content). Appended as
 * ?v=<token> so an edited catalog is fetched fresh instead of served stale from
 * the browser / service-worker cache. "dev" when unbundled (build:dev / tests).
 */
const SHIPPED_GUIDE_VER = (typeof __GUIDE_VER__ !== "undefined") ? __GUIDE_VER__ : "dev";

/**
 * The guide catalog registered for a language, or undefined. English is always
 * present (bundled). Callers do the family/component lookup + fallback chain.
 *
 * @param {string} lang
 * @returns {object|undefined}
 */
export function guideCatalog(lang) {
  return GUIDE_CATALOGS[lang];
}

/**
 * Register a runtime-loaded catalog under `lang`. English is NOT overridable (it
 * is the bundled base + universal fallback — a partial/hostile en would break
 * fallback for every language). Rejects a non-object payload.
 *
 * @param {string} lang
 * @param {object} catalog
 * @returns {boolean} whether it registered.
 */
export function registerGuideCatalog(lang, catalog) {
  if (!lang || lang === "en") return false;
  if (!catalog || typeof catalog !== "object" || Array.isArray(catalog)) return false;
  GUIDE_CATALOGS[lang] = catalog;
  return true;
}

/**
 * Fetch + register one served guide catalog. JSON-only (no eval/import),
 * same-origin, fails soft to `false`.
 *
 * @param {string} url - same-origin guide JSON url.
 * @param {string} lang - language code to register under.
 * @param {{ fetchImpl?: typeof fetch }} [opts] - injectable fetch (tests).
 * @returns {Promise<boolean>}
 */
export async function loadGuideCatalog(url, lang, opts = {}) {
  const doFetch = opts.fetchImpl || (typeof fetch === "function" ? fetch : null);
  if (!doFetch || !lang || lang === "en") return false;
  try {
    const resp = await doFetch(url, { credentials: "same-origin" });
    if (!resp || !resp.ok) return false;
    const data = await resp.json();
    return registerGuideCatalog(lang, data);
  } catch {
    return false;
  }
}

/** Languages already fetched (or in flight). `en` is bundled, never fetched. */
const _requestedLangs = new Set(["en"]);

/**
 * Load ONLY the guide catalog(s) a card language needs — the language itself and,
 * for a regional tag (pt-BR → pt), its base — once each, ON DEMAND.
 *
 * Guides are NOT the UI locales: the guide text shows in one view in one language
 * at a time, so pulling all ~17 would just re-download most of what left the JS
 * bundle. A single language file is ~200 KB and fetches in ~10 ms (sub-second even
 * on a poor connection), and English (bundled) renders until it arrives — so a
 * globe switch is English → translated, never blank. `onLoaded` re-renders when a
 * catalog lands. Marks a code requested BEFORE the fetch so a persistent 404 (a
 * language with no served file) can't retry every render. Fails soft.
 *
 * @param {string} lang - the card's resolved language.
 * @param {() => void} [onLoaded]
 * @param {{ fetchImpl?: typeof fetch, baseUrl?: string, ver?: string }} [opts]
 */
export function ensureGuideLanguage(lang, onLoaded, opts = {}) {
  const full = String(lang || "en");
  const base = full.split("-")[0];
  const wanted = [];
  for (const code of [full, base]) {
    if (code && code !== "en" && !_requestedLangs.has(code) && !wanted.includes(code)) wanted.push(code);
  }
  if (!wanted.length) return Promise.resolve([]);
  for (const code of wanted) _requestedLangs.add(code);
  const baseUrl = opts.baseUrl || "/eufy_vacuum/frontend/guides";
  const ver = opts.ver ?? SHIPPED_GUIDE_VER;
  const bust = ver ? `?v=${encodeURIComponent(ver)}` : "";
  return Promise.all(
    wanted.map((code) => loadGuideCatalog(`${baseUrl}/${code}.json${bust}`, code, opts)),
  ).then((results) => {
    if (results.some(Boolean) && typeof onLoaded === "function") onLoaded();
    return wanted.filter((_, i) => results[i]);
  });
}
