"""Built-in (preloaded) theme definitions.

Contains the build helpers, base spec, preloaded theme list, and the
one-time library seeder.  Everything here is pure data — no HA imports,
no storage, no callbacks.  Extracted verbatim from core/manager.py.
"""

from __future__ import annotations

from typing import Any


# ---------------------------------------------------------------------------
# Build helpers
# ---------------------------------------------------------------------------


def _build_preloaded_theme_entry(
    theme_id: str,
    name: str,
    *,
    colors: dict[str, Any] | None = None,
    tokens: dict[str, Any] | None = None,
    alpha: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build one preloaded theme entry with canonical token duplication."""
    color_values = dict(colors or {})
    token_values = {
        **color_values,
        **dict(tokens or {}),
    }
    return {
        "id": theme_id,
        "name": name,
        # Bundled themes carry the `core` provenance — the card/gallery Source
        # facet reads this to tell shipped themes apart from user/community ones.
        "source": "core",
        "tokens": token_values,
        "colors": color_values,
        "alpha": dict(alpha or {}),
    }


def _build_release_theme_colors(
    *,
    accent: str,
    surface_base: str,
    surface_panel: str,
    surface_raised: str,
    surface_input: str,
    surface_overlay: str,
    text_primary: str,
    text_secondary: str,
    text_muted: str,
    border_subtle: str,
    border_default: str,
    border_strong: str,
    sem_success: str,
    sem_warning: str,
    sem_error: str,
    sem_info: str,
) -> dict[str, str]:
    """Return a broad release-ready theme color layer."""
    return {
        "--evcc-accent": accent,
        "--evcc-text-muted": text_muted,
        "--evcc-text-primary": text_primary,
        "--evcc-text-secondary": text_secondary,
        "--evcc-bg-input": "var(--evcc-surface-input)",
        "--evcc-card-bg": "var(--evcc-surface-card)",
        "--evcc-panel-bg": "var(--evcc-surface-panel)",
        "--evcc-surface-base": surface_base,
        "--evcc-surface-card": "var(--evcc-surface-base)",
        "--evcc-surface-input": surface_input,
        "--evcc-surface-overlay": surface_overlay,
        "--evcc-surface-panel": surface_panel,
        "--evcc-surface-raised": surface_raised,
        "--evcc-border-default": border_default,
        "--evcc-border-strong": border_strong,
        "--evcc-border-subtle": border_subtle,
        "--evcc-chip-active-bg": "color-mix(in srgb, var(--evcc-accent) 18%, transparent)",
        "--evcc-chip-active-border": "color-mix(in srgb, var(--evcc-accent) 42%, transparent)",
        "--evcc-chip-active-text": "var(--evcc-accent)",
        "--evcc-chip-bg": "var(--evcc-surface-input)",
        "--evcc-chip-border": "var(--evcc-border-default)",
        "--evcc-chip-excluded-bg": "color-mix(in srgb, var(--evcc-sem-error) 12%, transparent)",
        "--evcc-chip-excluded-border": "color-mix(in srgb, var(--evcc-sem-error) 32%, transparent)",
        "--evcc-chip-excluded-text": "color-mix(in srgb, var(--evcc-sem-error) 85%, white 15%)",
        "--evcc-chip-hover-bg": "var(--evcc-surface-panel)",
        "--evcc-chip-hover-border": "var(--evcc-border-strong)",
        "--evcc-chip-hover-text": "var(--evcc-text-primary)",
        "--evcc-chip-included-bg": "color-mix(in srgb, var(--evcc-sem-success) 14%, transparent)",
        "--evcc-chip-included-border": "color-mix(in srgb, var(--evcc-sem-success) 34%, transparent)",
        "--evcc-chip-included-text": "color-mix(in srgb, var(--evcc-sem-success) 82%, white 18%)",
        "--evcc-chip-neutral-bg": "color-mix(in srgb, var(--evcc-surface-raised) 82%, transparent)",
        "--evcc-chip-success-bg": "color-mix(in srgb, var(--evcc-sem-success) 16%, transparent)",
        "--evcc-chip-success-border": "color-mix(in srgb, var(--evcc-sem-success) 36%, transparent)",
        "--evcc-chip-success-text": "color-mix(in srgb, var(--evcc-sem-success) 82%, white 18%)",
        "--evcc-chip-text": "var(--evcc-text-secondary)",
        "--evcc-chip-warning-bg": "color-mix(in srgb, var(--evcc-sem-warning) 16%, transparent)",
        "--evcc-chip-warning-border": "color-mix(in srgb, var(--evcc-sem-warning) 38%, transparent)",
        "--evcc-chip-warning-text": "color-mix(in srgb, var(--evcc-sem-warning) 80%, white 20%)",
        "--evcc-profile-chip-bg": "color-mix(in srgb, var(--evcc-surface-input) 92%, transparent)",
        "--evcc-profile-chip-border": "var(--evcc-border-default)",
        "--evcc-profile-chip-custom-bg": "color-mix(in srgb, var(--evcc-accent) 16%, transparent)",
        "--evcc-profile-chip-custom-border": "color-mix(in srgb, var(--evcc-accent) 36%, transparent)",
        "--evcc-profile-chip-custom-text": "var(--evcc-accent)",
        "--evcc-profile-chip-text": "var(--evcc-text-secondary)",
        "--evcc-room-chip-bg": "color-mix(in srgb, var(--evcc-surface-panel) 88%, transparent)",
        "--evcc-room-chip-border": "var(--evcc-border-default)",
        "--evcc-room-chip-text": "var(--evcc-text-secondary)",
        "--evcc-order-chip-bg": "color-mix(in srgb, var(--evcc-accent) 14%, transparent)",
        "--evcc-order-chip-border": "color-mix(in srgb, var(--evcc-accent) 36%, transparent)",
        "--evcc-order-chip-text": "var(--evcc-accent)",
        "--evcc-order-feedback-border": "color-mix(in srgb, var(--evcc-accent) 44%, transparent)",
        "--evcc-order-target-outline": "color-mix(in srgb, var(--evcc-accent) 60%, transparent)",
        "--evcc-progress-fill": "var(--evcc-accent)",
        "--evcc-queue-chip-bg": "var(--evcc-surface-input)",
        "--evcc-queue-chip-border": "var(--evcc-border-default)",
        "--evcc-queue-chip-text": "var(--evcc-text-secondary)",
        "--evcc-queue-completed-bg": "color-mix(in srgb, var(--evcc-sem-success) 14%, transparent)",
        "--evcc-queue-completed-border": "color-mix(in srgb, var(--evcc-sem-success) 34%, transparent)",
        "--evcc-queue-completed-text": "color-mix(in srgb, var(--evcc-sem-success) 80%, white 20%)",
        "--evcc-queue-current-bg": "color-mix(in srgb, var(--evcc-accent) 18%, transparent)",
        "--evcc-queue-current-border": "color-mix(in srgb, var(--evcc-accent) 40%, transparent)",
        "--evcc-queue-current-text": "var(--evcc-accent)",
        "--evcc-queue-hover-bg": "var(--evcc-surface-panel)",
        "--evcc-queue-hover-border": "var(--evcc-border-strong)",
        "--evcc-queue-hover-text": "var(--evcc-text-primary)",
        "--evcc-queue-inferred-bg": "color-mix(in srgb, var(--evcc-sem-info) 14%, transparent)",
        "--evcc-queue-inferred-border": "color-mix(in srgb, var(--evcc-sem-info) 36%, transparent)",
        "--evcc-queue-inferred-text": "var(--evcc-sem-info)",
        "--evcc-queue-order-bg": "color-mix(in srgb, var(--evcc-surface-raised) 88%, transparent)",
        "--evcc-queue-order-border": "var(--evcc-border-default)",
        "--evcc-queue-order-text": "var(--evcc-text-secondary)",
        "--evcc-queue-pending-bg": "color-mix(in srgb, var(--evcc-surface-input) 94%, transparent)",
        "--evcc-queue-pending-border": "var(--evcc-border-subtle)",
        "--evcc-queue-pending-text": "var(--evcc-text-secondary)",
        "--evcc-queue-skipped-bg": "color-mix(in srgb, var(--evcc-sem-warning) 12%, transparent)",
        "--evcc-queue-skipped-border": "color-mix(in srgb, var(--evcc-sem-warning) 30%, transparent)",
        "--evcc-queue-skipped-text": "color-mix(in srgb, var(--evcc-sem-warning) 80%, white 20%)",
        "--evcc-color-cleaning": "var(--evcc-sem-success)",
        "--evcc-color-docked": "var(--evcc-accent)",
        "--evcc-color-error": "var(--evcc-sem-error)",
        "--evcc-color-idle": "var(--evcc-text-secondary)",
        "--evcc-confidence-high-bg": "color-mix(in srgb, var(--evcc-sem-success) 14%, transparent)",
        "--evcc-confidence-high-border": "color-mix(in srgb, var(--evcc-sem-success) 34%, transparent)",
        "--evcc-confidence-high-text": "color-mix(in srgb, var(--evcc-sem-success) 82%, white 18%)",
        "--evcc-confidence-low-bg": "color-mix(in srgb, var(--evcc-sem-error) 14%, transparent)",
        "--evcc-confidence-low-border": "color-mix(in srgb, var(--evcc-sem-error) 34%, transparent)",
        "--evcc-confidence-low-text": "color-mix(in srgb, var(--evcc-sem-error) 82%, white 18%)",
        "--evcc-confidence-medium-bg": "color-mix(in srgb, var(--evcc-sem-warning) 14%, transparent)",
        "--evcc-confidence-medium-border": "color-mix(in srgb, var(--evcc-sem-warning) 34%, transparent)",
        "--evcc-confidence-medium-text": "color-mix(in srgb, var(--evcc-sem-warning) 82%, white 18%)",
        "--evcc-sem-error": sem_error,
        "--evcc-sem-info": sem_info,
        "--evcc-sem-success": sem_success,
        "--evcc-sem-warning": sem_warning,
        "--evcc-status-cleaning-bg": "color-mix(in srgb, var(--evcc-sem-success) 16%, transparent)",
        "--evcc-status-cleaning-border": "color-mix(in srgb, var(--evcc-sem-success) 34%, transparent)",
        "--evcc-status-cleaning-text": "color-mix(in srgb, var(--evcc-sem-success) 82%, white 18%)",
        "--evcc-status-dot-charging": "var(--evcc-accent)",
        "--evcc-status-dot-cleaning": "var(--evcc-sem-success)",
        "--evcc-status-dot-docked": "var(--evcc-accent)",
        "--evcc-status-dot-error": "var(--evcc-sem-error)",
        "--evcc-status-dot-idle": "var(--evcc-text-secondary)",
        "--evcc-status-dot-offline": "var(--evcc-text-muted)",
        "--evcc-status-dot-paused": "var(--evcc-sem-warning)",
        "--evcc-status-dot-returning": "var(--evcc-sem-warning)",
        "--evcc-status-dot-unavailable": "var(--evcc-text-muted)",
        "--evcc-estimate-default-bg": "color-mix(in srgb, var(--evcc-surface-input) 96%, transparent)",
        "--evcc-estimate-default-border": "var(--evcc-border-default)",
        "--evcc-estimate-default-text": "var(--evcc-text-secondary)",
        "--evcc-estimate-learned-bg": "color-mix(in srgb, var(--evcc-accent) 14%, transparent)",
        "--evcc-estimate-learned-border": "color-mix(in srgb, var(--evcc-accent) 34%, transparent)",
        "--evcc-estimate-learned-text": "var(--evcc-accent)",
        "--evcc-learning-confidence-high-bg": "color-mix(in srgb, var(--evcc-sem-success) 14%, transparent)",
        "--evcc-learning-confidence-high-border": "color-mix(in srgb, var(--evcc-sem-success) 34%, transparent)",
        "--evcc-learning-confidence-high-text": "color-mix(in srgb, var(--evcc-sem-success) 82%, white 18%)",
        "--evcc-learning-confidence-low-border": "color-mix(in srgb, var(--evcc-sem-error) 34%, transparent)",
        "--evcc-learning-confidence-low-text": "color-mix(in srgb, var(--evcc-sem-error) 82%, white 18%)",
        "--evcc-learning-confidence-medium-bg": "color-mix(in srgb, var(--evcc-sem-warning) 14%, transparent)",
        "--evcc-learning-confidence-medium-border": "color-mix(in srgb, var(--evcc-sem-warning) 34%, transparent)",
        "--evcc-learning-confidence-medium-text": "color-mix(in srgb, var(--evcc-sem-warning) 82%, white 18%)",
        "--evcc-learning-confidence-neutral-border": "var(--evcc-border-default)",
        "--evcc-learning-confidence-neutral-text": "var(--evcc-text-secondary)",
        "--evcc-learning-note-text": "var(--evcc-text-secondary)",
        "--evcc-learning-panel-bg": "var(--evcc-surface-panel)",
        "--evcc-learning-panel-border": "var(--evcc-border-default)",
        "--evcc-learning-reanchor-border": "color-mix(in srgb, var(--evcc-accent) 34%, transparent)",
        "--evcc-learning-reanchor-highlight": "color-mix(in srgb, var(--evcc-accent) 22%, transparent)",
        "--evcc-learning-text-muted": "var(--evcc-text-muted)",
        "--evcc-learning-text-primary": "var(--evcc-text-primary)",
        "--evcc-learning-text-secondary": "var(--evcc-text-secondary)",
        "--evcc-learning-warning-text": "color-mix(in srgb, var(--evcc-sem-warning) 82%, white 18%)",
        "--evcc-modal-accent": "var(--evcc-accent)",
        "--evcc-modal-accent-bg": "color-mix(in srgb, var(--evcc-accent) 22%, transparent)",
        "--evcc-modal-accent-border": "color-mix(in srgb, var(--evcc-accent) 42%, transparent)",
        "--evcc-modal-accent-text": "var(--evcc-accent)",
        "--evcc-modal-backdrop-bg": "var(--evcc-surface-overlay)",
        "--evcc-modal-bg": "color-mix(in srgb, var(--evcc-surface-base) 92%, black 8%)",
        "--evcc-modal-border": "var(--evcc-border-default)",
        "--evcc-modal-border-default": "var(--evcc-border-default)",
        "--evcc-modal-border-strong": "var(--evcc-border-strong)",
        "--evcc-modal-border-subtle": "var(--evcc-border-subtle)",
        "--evcc-modal-chip-active-bg": "var(--evcc-modal-accent-bg)",
        "--evcc-modal-chip-active-border": "var(--evcc-modal-accent-border)",
        "--evcc-modal-chip-active-text": "var(--evcc-modal-accent-text)",
        "--evcc-modal-chip-bg": "var(--evcc-surface-input)",
        "--evcc-modal-chip-border": "var(--evcc-border-default)",
        "--evcc-modal-chip-hover-bg": "var(--evcc-surface-panel)",
        "--evcc-modal-chip-hover-border": "var(--evcc-border-strong)",
        "--evcc-modal-chip-hover-text": "var(--evcc-text-primary)",
        "--evcc-modal-chip-text": "var(--evcc-text-secondary)",
        "--evcc-modal-footer-bg": "color-mix(in srgb, var(--evcc-surface-panel) 80%, transparent)",
        "--evcc-modal-header-bg": "color-mix(in srgb, var(--evcc-surface-panel) 86%, transparent)",
        "--evcc-modal-input-bg": "var(--evcc-surface-input)",
        "--evcc-modal-surface-input": "var(--evcc-surface-input)",
        "--evcc-modal-surface-panel": "var(--evcc-surface-panel)",
        "--evcc-modal-surface-section": "var(--evcc-surface-raised)",
        "--evcc-modal-text-muted": "var(--evcc-text-muted)",
        "--evcc-modal-text-primary": "var(--evcc-text-primary)",
        "--evcc-modal-text-secondary": "var(--evcc-text-secondary)",
        "--evcc-modal-warning-bg": "color-mix(in srgb, var(--evcc-sem-warning) 16%, transparent)",
        "--evcc-modal-warning-border": "color-mix(in srgb, var(--evcc-sem-warning) 34%, transparent)",
        "--evcc-modal-warning-text": "color-mix(in srgb, var(--evcc-sem-warning) 82%, white 18%)",
    }


def _build_release_theme_tokens(spec: dict[str, Any]) -> dict[str, Any]:
    """Return non-color release theme tokens."""
    return {
        "--evcc-font-family": spec["font_family"],
        "--evcc-gap": spec["gap"],
        "--evcc-grid-gap": spec["grid_gap"],
        "--evcc-hover-lift": spec["hover_lift"],
        "--evcc-pad": spec["pad"],
        "--evcc-press-scale": spec["press_scale"],
        "--evcc-radius-card": spec["radius_card"],
        "--evcc-radius-chip": spec["radius_chip"],
        "--evcc-radius-inner": spec["radius_inner"],
        "--evcc-radius-panel": spec["radius_panel"],
        "--evcc-section-gap": spec["section_gap"],
        "--evcc-space-sm": spec["space_sm"],
        "--evcc-space-md": spec["space_md"],
        "--evcc-space-lg": spec["space_lg"],
        "--evcc-transition-normal": spec["transition_normal"],
        "--evcc-chip-font-size": spec["chip_font_size"],
        "--evcc-chip-font-weight": spec["chip_font_weight"],
        "--evcc-chip-gap": spec["chip_gap"],
        "--evcc-chip-height": spec["chip_height"],
        "--evcc-chip-icon-height": spec["chip_icon_height"],
        "--evcc-chip-icon-padding": spec["chip_icon_padding"],
        "--evcc-chip-icon-size": spec["chip_icon_size"],
        "--evcc-chip-padding": spec["chip_padding"],
        "--evcc-chip-radius": spec["chip_radius"],
        "--evcc-room-fill-opacity": spec["room_fill_opacity"],
        "--evcc-room-grid-columns": spec["room_grid_columns"],
        "--evcc-room-grid-gap": spec["room_grid_gap"],
        "--evcc-room-grid-min": spec["room_grid_min"],
        "--evcc-queue-chip-gap": spec["queue_chip_gap"],
        "--evcc-queue-completed-opacity": spec["queue_completed_opacity"],
        "--evcc-queue-pending-opacity": spec["queue_pending_opacity"],
        "--evcc-drag-opacity": spec["drag_opacity"],
        "--evcc-drag-scale": spec["drag_scale"],
        "--evcc-progress-complete": "100%",
        "--evcc-learning-anim-ease": spec["learning_anim_ease"],
        "--evcc-learning-chip-font-size": spec["learning_chip_font_size"],
        "--evcc-learning-chip-font-weight": spec["learning_chip_font_weight"],
        "--evcc-learning-chip-radius": spec["learning_chip_radius"],
        "--evcc-learning-confidence-high-gradient": spec["learning_high_gradient"],
        "--evcc-learning-confidence-medium-gradient": spec["learning_medium_gradient"],
        "--evcc-learning-confidence-low-gradient": spec["learning_low_gradient"],
        "--evcc-learning-confidence-neutral-gradient": spec["learning_neutral_gradient"],
        "--evcc-modal-backdrop-blur": spec["modal_backdrop_blur"],
        "--evcc-modal-padding": spec["modal_padding"],
        "--evcc-modal-radius": spec["modal_radius"],
        "--evcc-modal-section-gap": spec["modal_section_gap"],
    }


# ---------------------------------------------------------------------------
# Base spec and preloaded theme list
# ---------------------------------------------------------------------------

BASE_PRELOADED_THEME_SPEC: dict[str, Any] = {
    "font_family": '"Segoe UI", "Inter", system-ui, sans-serif',
    "gap": "12px",
    "grid_gap": "12px",
    "hover_lift": "-1px",
    "pad": "16px",
    "press_scale": 0.985,
    "radius_card": "14px",
    "radius_chip": "999px",
    "radius_inner": "9px",
    "radius_panel": "16px",
    "section_gap": "18px",
    "space_sm": "8px",
    "space_md": "12px",
    "space_lg": "16px",
    "transition_normal": "160ms ease",
    "chip_font_size": "0.82rem",
    "chip_font_weight": "560",
    "chip_gap": "6px",
    "chip_height": "24px",
    "chip_icon_height": "24px",
    "chip_icon_padding": "4px 8px",
    "chip_icon_size": "0.8rem",
    "chip_padding": "5px 14px",
    "chip_radius": "999px",
    "room_fill_opacity": 0.22,
    "room_grid_columns": "repeat(auto-fit, minmax(170px, 1fr))",
    "room_grid_gap": "12px",
    "room_grid_min": "170px",
    "queue_chip_gap": "6px",
    "queue_completed_opacity": 0.72,
    "queue_pending_opacity": 0.9,
    "drag_opacity": 0.92,
    "drag_scale": 1.02,
    "learning_anim_ease": "cubic-bezier(0.2, 0.8, 0.2, 1)",
    "learning_chip_font_size": "0.8rem",
    "learning_chip_font_weight": "600",
    "learning_chip_radius": "999px",
    "modal_backdrop_blur": 10,
    "modal_padding": "18px",
    "modal_radius": "18px",
    "modal_section_gap": "24px",
    "learning_high_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-success) 28%, transparent), transparent)",
    "learning_medium_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-warning) 24%, transparent), transparent)",
    "learning_low_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-error) 24%, transparent), transparent)",
    "learning_neutral_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-surface-raised) 70%, transparent), transparent)",
}


PRELOADED_THEME_SPECS: list[dict[str, Any]] = [
    {"id": "theme_follow_ha", "name": "Follow HA Theme", "colors": {}, "tokens": {}},
    {
        "id": "theme_core_slate",
        "name": "Core Slate",
        "colors": _build_release_theme_colors(
            accent="#6AA7FF",
            surface_base="#1B2129",
            surface_panel="#232B35",
            surface_raised="#2A3340",
            surface_input="rgba(255,255,255,0.06)",
            surface_overlay="rgba(4,8,14,0.58)",
            text_primary="#EEF3F8",
            text_secondary="rgba(238,243,248,0.74)",
            text_muted="rgba(238,243,248,0.50)",
            border_subtle="rgba(255,255,255,0.06)",
            border_default="rgba(255,255,255,0.11)",
            border_strong="rgba(255,255,255,0.19)",
            sem_success="#62C98F",
            sem_warning="#EAB25B",
            sem_error="#E16C6C",
            sem_info="#7DB4FF",
        ),
        "tokens": _build_release_theme_tokens(BASE_PRELOADED_THEME_SPEC),
    },
    {
        "id": "theme_forest_night",
        "name": "Forest Night",
        "colors": _build_release_theme_colors(
            accent="#7CCF8A",
            surface_base="#15201A",
            surface_panel="#1D2B22",
            surface_raised="#25362B",
            surface_input="rgba(154,209,171,0.08)",
            surface_overlay="rgba(4,10,6,0.62)",
            text_primary="#EDF7EF",
            text_secondary="rgba(237,247,239,0.74)",
            text_muted="rgba(237,247,239,0.50)",
            border_subtle="rgba(185,220,191,0.08)",
            border_default="rgba(185,220,191,0.14)",
            border_strong="rgba(185,220,191,0.24)",
            sem_success="#76D79A",
            sem_warning="#D8B15B",
            sem_error="#D97979",
            sem_info="#8DC9B4",
        ),
        "tokens": _build_release_theme_tokens({**BASE_PRELOADED_THEME_SPEC, "font_family": '"Segoe UI", "Aptos", system-ui, sans-serif', "radius_card": "15px", "radius_inner": "10px", "radius_panel": "18px", "transition_normal": "170ms ease", "learning_anim_ease": "cubic-bezier(0.18, 0.82, 0.22, 1)", "room_fill_opacity": 0.24, "learning_high_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-success) 32%, transparent), transparent)", "learning_neutral_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-surface-raised) 72%, transparent), transparent)"}),
    },
    {
        "id": "theme_soft_carbon",
        "name": "Soft Carbon",
        "colors": _build_release_theme_colors(
            accent="#89A8D8",
            surface_base="#1D1F23",
            surface_panel="#25282D",
            surface_raised="#2D3138",
            surface_input="rgba(255,255,255,0.05)",
            surface_overlay="rgba(6,8,12,0.60)",
            text_primary="#F1F4F7",
            text_secondary="rgba(241,244,247,0.72)",
            text_muted="rgba(241,244,247,0.48)",
            border_subtle="rgba(255,255,255,0.05)",
            border_default="rgba(255,255,255,0.10)",
            border_strong="rgba(255,255,255,0.16)",
            sem_success="#73CFA0",
            sem_warning="#D8A75B",
            sem_error="#D97878",
            sem_info="#8BAFE4",
        ),
        "tokens": _build_release_theme_tokens({**BASE_PRELOADED_THEME_SPEC, "press_scale": 0.988, "radius_card": "13px", "radius_inner": "8px", "radius_panel": "15px", "transition_normal": "145ms ease", "chip_font_size": "0.81rem", "chip_font_weight": "540", "room_fill_opacity": 0.20, "drag_opacity": 0.90, "drag_scale": 1.015, "learning_anim_ease": "ease", "learning_chip_font_size": "0.79rem", "learning_chip_font_weight": "580", "modal_backdrop_blur": 9, "modal_radius": "16px", "modal_section_gap": "22px", "learning_high_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-success) 24%, transparent), transparent)", "learning_medium_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-warning) 20%, transparent), transparent)", "learning_low_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-error) 20%, transparent), transparent)", "learning_neutral_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-surface-raised) 64%, transparent), transparent)"}),
    },
    {
        "id": "theme_warm_light",
        "name": "Warm Light",
        "colors": _build_release_theme_colors(
            accent="#8C6A3C",
            surface_base="#F3EFE7",
            surface_panel="#E7E0D3",
            surface_raised="#FBF7F0",
            surface_input="rgba(72,54,34,0.06)",
            surface_overlay="rgba(38,26,14,0.16)",
            text_primary="#2F2418",
            text_secondary="rgba(47,36,24,0.72)",
            text_muted="rgba(47,36,24,0.50)",
            border_subtle="rgba(66,49,30,0.08)",
            border_default="rgba(66,49,30,0.14)",
            border_strong="rgba(66,49,30,0.22)",
            sem_success="#4E9C69",
            sem_warning="#C48A2F",
            sem_error="#C45E5E",
            sem_info="#5C8BC8",
        ),
        "tokens": _build_release_theme_tokens({**BASE_PRELOADED_THEME_SPEC, "font_family": '"Segoe UI", "Aptos", system-ui, sans-serif', "press_scale": 0.987, "radius_card": "15px", "radius_panel": "18px", "room_fill_opacity": 0.18, "drag_scale": 1.018, "learning_anim_ease": "cubic-bezier(0.22, 0.78, 0.2, 1)", "modal_backdrop_blur": 8, "learning_high_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-success) 22%, white 4%), transparent)", "learning_medium_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-warning) 22%, white 4%), transparent)", "learning_low_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-error) 20%, white 4%), transparent)", "learning_neutral_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-surface-panel) 70%, white 6%), transparent)"}),
    },
    {
        "id": "theme_high_contrast",
        "name": "High Contrast",
        "colors": _build_release_theme_colors(
            accent="#2F8FFF",
            surface_base="#111317",
            surface_panel="#171B21",
            surface_raised="#1F242C",
            surface_input="rgba(255,255,255,0.08)",
            surface_overlay="rgba(0,0,0,0.72)",
            text_primary="#FFFFFF",
            text_secondary="rgba(255,255,255,0.84)",
            text_muted="rgba(255,255,255,0.64)",
            border_subtle="rgba(255,255,255,0.10)",
            border_default="rgba(255,255,255,0.18)",
            border_strong="rgba(255,255,255,0.30)",
            sem_success="#59D185",
            sem_warning="#FFBF47",
            sem_error="#FF6B6B",
            sem_info="#6EB7FF",
        ),
        "tokens": _build_release_theme_tokens({**BASE_PRELOADED_THEME_SPEC, "transition_normal": "135ms ease", "chip_font_size": "0.83rem", "chip_font_weight": "620", "radius_card": "12px", "radius_inner": "8px", "radius_panel": "14px", "room_fill_opacity": 0.26, "queue_completed_opacity": 0.78, "queue_pending_opacity": 0.92, "drag_opacity": 0.95, "drag_scale": 1.025, "learning_anim_ease": "linear", "learning_chip_font_size": "0.81rem", "learning_chip_font_weight": "650", "modal_backdrop_blur": 11, "modal_radius": "16px", "learning_high_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-success) 36%, transparent), transparent)", "learning_medium_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-warning) 34%, transparent), transparent)", "learning_low_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-sem-error) 34%, transparent), transparent)", "learning_neutral_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-border-strong) 70%, transparent), transparent)"}),
    },
    {
        "id": "theme_colorblind_safe",
        "name": "Colorblind Safe",
        "colors": _build_release_theme_colors(
            accent="#2F8FFF",
            surface_base="#111317",
            surface_panel="#171B21",
            surface_raised="#1F242C",
            surface_input="rgba(255,255,255,0.08)",
            surface_overlay="rgba(0,0,0,0.72)",
            text_primary="#FFFFFF",
            text_secondary="rgba(255,255,255,0.84)",
            text_muted="#BCC2C7",
            border_subtle="rgba(255,255,255,0.10)",
            border_default="rgba(255,255,255,0.18)",
            border_strong="rgba(255,255,255,0.30)",
            # CVD-safe semantic anchors — validated ΔE2000 >= 15 on all 10 group
            # pairs under Machado 2009 protan/deutan + Brettel 1997 tritan (full
            # dichromat severity). Keep in sync with harness/bundles/cvd-safe.mjs,
            # which the harness CVD gate (harness/tests/cvd.spec.mjs) validates.
            # Everything else (color-*, confidence-*, status-dot-*, learning-*)
            # cascades from these via var(). Paired with the always-on per-state
            # shape marks (src/renderers/badge-marks.js) so warn/likely — which
            # share the warning hue — stay distinguishable without color.
            sem_success="#0C8F86",
            sem_warning="#E9A100",
            sem_error="#D6403A",
            sem_info="#0F4C86",
        ),
        "tokens": _build_release_theme_tokens(BASE_PRELOADED_THEME_SPEC),
    },
    {
        "id": "theme_signal",
        "name": "Signal",
        "colors": _build_release_theme_colors(
            accent="#FF7B5A",
            surface_base="#201722",
            surface_panel="#2A1D2E",
            surface_raised="#34253A",
            surface_input="rgba(255,255,255,0.08)",
            surface_overlay="rgba(10,4,12,0.62)",
            text_primary="#F7EEF8",
            text_secondary="rgba(247,238,248,0.74)",
            text_muted="rgba(247,238,248,0.50)",
            border_subtle="rgba(255,215,225,0.08)",
            border_default="rgba(255,215,225,0.14)",
            border_strong="rgba(255,215,225,0.24)",
            sem_success="#66D79E",
            sem_warning="#F4BA5E",
            sem_error="#FF7676",
            sem_info="#8AB4FF",
        ),
        "tokens": _build_release_theme_tokens({**BASE_PRELOADED_THEME_SPEC, "font_family": '"Segoe UI", "Aptos", system-ui, sans-serif', "hover_lift": "-2px", "press_scale": 0.984, "radius_card": "16px", "radius_inner": "10px", "radius_panel": "18px", "transition_normal": "175ms cubic-bezier(0.2, 0.9, 0.2, 1)", "chip_font_weight": "600", "drag_scale": 1.03, "learning_anim_ease": "cubic-bezier(0.16, 0.88, 0.24, 1)", "learning_chip_font_weight": "620", "learning_neutral_gradient": "linear-gradient(135deg, color-mix(in srgb, var(--evcc-accent) 18%, transparent), transparent)"}),
    },
]


# ---------------------------------------------------------------------------
# Library seeder
# ---------------------------------------------------------------------------


def ensure_preloaded_theme_library(theme_data: dict[str, Any]) -> None:
    """Ensure the built-in theme library exists without clobbering user themes.

    Called once by ThemeManager.__init__() after storage is loaded so
    the per-call read path stays fast.
    """
    library = theme_data.setdefault("library", {})
    if not isinstance(library, dict):
        library = {}
        theme_data["library"] = library

    for spec in PRELOADED_THEME_SPECS:
        theme_id = spec["id"]
        if theme_id in library:
            # Migration: a bundled theme seeded by an older version (pre-`source`)
            # gets its provenance backfilled so the Source facet sees it as core.
            # Only OUR entries are touched — a user theme's provenance is unknown
            # and is left alone (new ones are stamped at save/import time).
            existing = library[theme_id]
            if isinstance(existing, dict):
                existing.setdefault("source", "core")
            continue
        library[theme_id] = _build_preloaded_theme_entry(
            theme_id,
            spec["name"],
            colors=spec.get("colors"),
            tokens=spec.get("tokens"),
            alpha=spec.get("alpha"),
        )

    default_theme_id = str(theme_data.get("default_theme_id") or "").strip()
    if not default_theme_id or default_theme_id not in library:
        theme_data["default_theme_id"] = "theme_follow_ha"
