"""Dreame upkeep catalog — model -> (display name, maintenance family).

family is either one of the 16 AUTHORED families (dreame_upkeep_guides.py) or a generic
name-derived TIER for the long tail. An authored family is assigned on an exact
authored-line name match, OR on a reg-code (PLATFORM) match proving the same certified
machine as an authored line — verify_rebadge_claims.py's rule "two names sharing an
r-code are the same hardware, proof not inference" (e.g. GoVac 800 == X50 on RLX85CE,
L10s Ultra Gen 3 / L40 Ultra Gen 2 == the L50 machine on RLH41CE, Aqua 10 Pro Track ==
Aqua10 Ultra Track on RLR81CE). Either way measured prose never lands on a
differently-mopped variant. Generic tiers are PROVISIONAL from the marketing name;
refine from the DEVICE_INFO capability table (AUTO_EMPTY / SELF_WASH / WATER_TANK /
MOP_PAD|ROLLER). Unauthored families fall back to `standard` in the manager. Model list
generated from supported_devices.md; family column hand-refined (no generator emits it)."""

from __future__ import annotations

# (device.model, display name, family). family PROVISIONAL; verify vs DEVICE_INFO.
DREAME_MODELS: list[tuple[str, str, str]] = [
    ("dreame.vacuum.r5109f", "Aqua10 Ultra Roller Master", "aqua10_ultra_roller"),
    ("dreame.vacuum.r9535a", "Aqua10 Ultra Roller", "aqua10_ultra_roller"),
    ("dreame.vacuum.r9535h", "Aqua10 Ultra Roller", "aqua10_ultra_roller"),
    ("dreame.vacuum.r9535n", "Aqua10 Ultra Roller", "aqua10_ultra_roller"),
    ("dreame.vacuum.r95475", "Aqua10 Ultra Roller Complete", "aqua10_ultra_roller"),
    ("dreame.vacuum.r95476", "Aqua10 Ultra Roller Complete", "aqua10_ultra_roller"),
    ("dreame.vacuum.r9547a", "Aqua10 Ultra Roller Complete", "aqua10_ultra_roller"),
    ("dreame.vacuum.r9547c", "Aqua10 Ultra Roller Complete", "aqua10_ultra_roller"),
    ("dreame.vacuum.r9547h", "Aqua10 Ultra Roller Complete", "aqua10_ultra_roller"),
    ("dreame.vacuum.r9547k", "Aqua10 Ultra Roller Complete", "aqua10_ultra_roller"),
    ("dreame.vacuum.r2527a", "Aqua10 Ultra Track", "aqua10_ultra_track"),
    ("dreame.vacuum.r2527g", "Aqua10 Ultra Track S", "aqua10_ultra_track"),
    ("dreame.vacuum.r2527h", "Aqua10 Ultra Track", "aqua10_ultra_track"),
    ("dreame.vacuum.r2527q", "Aqua10 Ultra Track S", "aqua10_ultra_track"),
    ("dreame.vacuum.r95285", "Aqua10 Ultra Track Complete", "aqua10_ultra_track"),
    ("dreame.vacuum.r9528a", "Aqua10 Ultra Track Complete", "aqua10_ultra_track"),
    ("dreame.vacuum.r9528h", "Aqua10 Ultra Track Complete", "aqua10_ultra_track"),
    ("dreame.vacuum.p2028a", "L10 Plus", "auto_empty"),
    ("dreame.vacuum.r2205", "D10 Plus", "auto_empty"),
    ("dreame.vacuum.r2240", "D10s Plus", "auto_empty"),
    ("dreame.vacuum.r2246", "S10 Plus", "auto_empty"),
    ("dreame.vacuum.r2247", "S10 Pro Plus", "auto_empty"),
    ("dreame.vacuum.r2253", "X20 Pro Plus", "auto_empty"),
    ("dreame.vacuum.r2273a", "X20 Pro Plus", "auto_empty"),
    ("dreame.vacuum.r2316p", "S20 Plus", "auto_empty"),
    ("dreame.vacuum.r2322", "D9 Plus", "auto_empty"),
    ("dreame.vacuum.r2332", "S20 Pro Plus", "auto_empty"),
    ("dreame.vacuum.r2360", "S20 Pro Plus (Hot Water)", "auto_empty"),
    ("dreame.vacuum.r2363", "L10s Plus", "auto_empty"),
    ("dreame.vacuum.r2363a", "L10s Plus", "auto_empty"),
    ("dreame.vacuum.r2363n", "L10s Plus SE", "auto_empty"),
    ("dreame.vacuum.r2383a", "S10 Plus", "auto_empty"),
    ("dreame.vacuum.r2383k", "S10 Plus", "auto_empty"),
    ("dreame.vacuum.r2398", "S20 Plus (Hot Water)", "auto_empty"),
    ("dreame.vacuum.r2423", "D10 Plus Gen 2", "auto_empty"),
    ("dreame.vacuum.r2423a", "C20 Plus", "auto_empty"),
    ("dreame.vacuum.r2459a", "E20 Plus", "auto_empty"),
    ("dreame.vacuum.r2459h", "E20 Plus", "auto_empty"),
    ("dreame.vacuum.r2459k", "E20 Plus", "auto_empty"),
    ("dreame.vacuum.r2459r", "E20 Plus", "auto_empty"),
    ("dreame.vacuum.r2463r", "E20 Pro Plus", "auto_empty"),
    ("dreame.vacuum.r2483", "X40 Pro Plus", "auto_empty"),
    ("dreame.vacuum.r2493", "X40 Pro Plus", "auto_empty"),
    ("dreame.vacuum.r2564b", "D20 Plus", "d20_plus"),
    ("dreame.vacuum.r2564z", "D20 Plus", "d20_plus"),
    ("dreame.vacuum.r2566a", "D20 Pro Plus", "d20_pro_plus"),
    ("dreame.vacuum.r2566h", "D20 Pro Plus", "d20_pro_plus"),
    ("dreame.vacuum.r5049", "X50 Plus", "auto_empty"),
    ("dreame.vacuum.r5061", "S50 Plus", "auto_empty"),
    ("dreame.vacuum.r53148", "D20 Plus", "d20_plus"),
    ("dreame.vacuum.r5314a", "D20 Plus", "d20_plus"),
    ("dreame.vacuum.r5314z", "D20 Plus", "d20_plus"),
    ("dreame.vacuum.r531ra", "D20 Air Plus", "auto_empty"),
    ("dreame.vacuum.r531rh", "D20 Air Plus", "auto_empty"),
    ("dreame.vacuum.r53456", "L40 Plus", "auto_empty"),
    ("dreame.vacuum.r5345b", "L40 Plus", "auto_empty"),
    ("dreame.vacuum.r5345e", "L20s Plus", "auto_empty"),
    ("dreame.vacuum.r63014", "C30 Plus", "auto_empty"),
    ("dreame.vacuum.r63015", "GoVac 205 Plus", "auto_empty"),
    ("dreame.vacuum.r63017", "D20 Air Plus", "auto_empty"),
    ("dreame.vacuum.r6301a", "F20 Plus", "auto_empty"),
    ("dreame.vacuum.r6301h", "F20 Plus", "auto_empty"),
    ("dreame.vacuum.r6301r", "F21 Plus", "auto_empty"),
    ("dreame.vacuum.r6301v", "F21 Plus", "auto_empty"),
    ("dreame.vacuum.r9305", "S10 Pro Plus (Mop Pad Swing)", "auto_empty"),
    ("dreame.vacuum.r9524a", "F10 Plus", "auto_empty"),
    ("dreame.vacuum.r9524c", "D15 Plus", "auto_empty"),
    ("dreame.vacuum.r9524h", "F10 Plus", "auto_empty"),
    ("dreame.vacuum.r9524j", "F10 Plus", "auto_empty"),
    ("dreame.vacuum.r9524k", "D15 Plus", "auto_empty"),
    ("dreame.vacuum.r9524m", "F10 Plus", "auto_empty"),
    ("dreame.vacuum.r95275", "F21 Plus", "auto_empty"),
    ("dreame.vacuum.r95276", "C30 Plus", "auto_empty"),
    ("dreame.vacuum.r95277", "F20 Eco Plus", "auto_empty"),
    ("dreame.vacuum.r95278", "F21 Plus", "auto_empty"),
    ("dreame.vacuum.r95279", "Govac 205 plus", "auto_empty"),
    ("dreame.vacuum.r9527a", "F20 Plus", "auto_empty"),
    ("dreame.vacuum.r9527f", "F21 Plus", "auto_empty"),
    ("dreame.vacuum.r9527v", "F20 Plus", "auto_empty"),
    ("dreame.vacuum.r9537a", "D20 Pro Plus", "d20_pro_plus"),
    ("dreame.vacuum.r9537h", "D20 Pro Plus", "d20_pro_plus"),
    ("mova.vacuum.r2534h", "E30 Pro Plus", "auto_empty"),
    ("mova.vacuum.r2567a", "E20s Pro Plus", "auto_empty"),
    ("trouver.vacuum.r2567r", "E20s Pro Plus", "auto_empty"),
    ("dreame.vacuum.r2469a", "L10s Ultra Gen 2", "l10s_gen2"),
    ("dreame.vacuum.r2469x", "L10s Ultra Gen 2", "l10s_gen2"),
    ("dreame.vacuum.r5020a", "L10s Ultra Gen 2", "l10s_gen2"),
    ("dreame.vacuum.r2253b", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2253c", "L20 Ultra Complete", "l20"),
    ("dreame.vacuum.r2253d", "L20 Ultra Complete", "l20"),
    ("dreame.vacuum.r2253m", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2253t", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2253u", "L20 Ultra Complete", "l20"),
    ("dreame.vacuum.r2253w", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2338", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2394a", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2394f", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2394j", "L20 Ultra Complete", "l20"),
    ("dreame.vacuum.r2394k", "L20 Ultra Complete", "l20"),
    ("dreame.vacuum.r2394l", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2394s", "L20 Ultra", "l20"),
    ("dreame.vacuum.r2394u", "L20 Ultra Complete", "l20"),
    ("dreame.vacuum.r501s", "L50 Ultra CE", "l50"),
    ("dreame.vacuum.r5024b", "L50 Ultra CE", "l50"),
    ("dreame.vacuum.r502la", "L50 Ultra AE", "l50"),
    ("dreame.vacuum.r5061a", "L50 Ultra AE", "l50"),
    ("dreame.vacuum.r9493a", "L50 Ultra", "l50"),
    ("dreame.vacuum.r9493h", "L50 Ultra", "l50"),
    ("deerma.vacuum.a2403", "S30", "standard"),
    ("deerma.vacuum.a2404", "X70", "standard"),
    ("dreame.vacuum.ma1808", "1C", "standard"),
    ("dreame.vacuum.mb1808", "2C", "standard"),
    ("dreame.vacuum.mc1808", "2C", "standard"),
    ("dreame.vacuum.md1808", "1C", "standard"),
    ("dreame.vacuum.p2008", "F9", "standard"),
    ("dreame.vacuum.p2009", "D9", "standard"),
    ("dreame.vacuum.p2027", "W10", "standard"),
    ("dreame.vacuum.p2028", "Z10 Pro", "standard"),
    ("dreame.vacuum.p2029", "L10 Pro", "standard"),
    ("dreame.vacuum.p2036", "LDS Finder", "standard"),
    ("dreame.vacuum.p2041", "1T", "standard"),
    ("dreame.vacuum.p2041o", "Mi Robot Vacuum-Mop 2 Pro+", "standard"),
    ("dreame.vacuum.p2114a", "X10+", "standard"),
    ("dreame.vacuum.p2114o", "Self-Cleaning Robot Vacuum-Mop", "standard"),
    ("dreame.vacuum.p2140", "2C", "standard"),
    ("dreame.vacuum.p2140a", "2C", "standard"),
    ("dreame.vacuum.p2140o", "Mi Robot Vacuum-Mop 2", "standard"),
    ("dreame.vacuum.p2140p", "Mi Robot Vacuum-Mop 2", "standard"),
    ("dreame.vacuum.p2140q", "Mi Robot Vacuum-Mop 2", "standard"),
    ("dreame.vacuum.p2149o", "Self-Cleaning Robot Vacuum-Mop Pro", "standard"),
    ("dreame.vacuum.p2150o", "Mi Robot Vacuum-Mop", "standard"),
    ("dreame.vacuum.p2156o", "Z500", "standard"),
    ("dreame.vacuum.p2157", "L600", "standard"),
    ("dreame.vacuum.p2187", "D9 Pro", "standard"),
    ("dreame.vacuum.p2259", "D9 Max", "standard"),
    ("dreame.vacuum.r2104", "W10 Pro", "standard"),
    ("dreame.vacuum.r2209", "X10", "standard"),
    ("dreame.vacuum.r2210", "Cleaning And Mopping Robot 2 Pro", "standard"),
    ("dreame.vacuum.r2211o", "S10+", "standard"),
    ("dreame.vacuum.r2215", "X10", "standard"),
    ("dreame.vacuum.r2216o", "L10s Pro", "standard"),
    ("dreame.vacuum.r2228", "S10", "standard"),
    ("dreame.vacuum.r2232a", "W10s Pro", "standard"),
    ("dreame.vacuum.r2232b", "L10s Prime", "standard"),
    ("dreame.vacuum.r2232c", "L10s Prime", "standard"),
    ("dreame.vacuum.r2232d", "L10s Prime", "standard"),
    ("dreame.vacuum.r2233", "S10 Pro", "standard"),
    ("dreame.vacuum.r2243", "D10s", "standard"),
    ("dreame.vacuum.r2250", "D10s Pro", "standard"),
    ("dreame.vacuum.r2251a", "L10 Prime", "standard"),
    ("dreame.vacuum.r2251o", "W10s", "standard"),
    ("dreame.vacuum.r2254", "1S", "standard"),
    ("dreame.vacuum.r2260", "C9", "standard"),
    ("dreame.vacuum.r2263", "X20 Pro", "standard"),
    ("dreame.vacuum.r2273", "X20 Pro", "standard"),
    ("dreame.vacuum.r2312", "D9 Max", "standard"),
    ("dreame.vacuum.r2312a", "D9 Max (White)", "standard"),
    ("dreame.vacuum.r2313", "S20 Pro", "standard"),
    ("dreame.vacuum.r2316", "S20", "standard"),
    ("dreame.vacuum.r2317", "W20", "standard"),
    ("dreame.vacuum.r2328", "F9 Pro", "standard"),
    ("dreame.vacuum.r2345a", "W20 Pro", "standard"),
    ("dreame.vacuum.r2350", "G20", "standard"),
    ("dreame.vacuum.r2355", "S20 Pro (Hot Water)", "standard"),
    ("dreame.vacuum.r2360w", "S10 Pro Max (Hot Water)", "standard"),
    ("dreame.vacuum.r2364", "L10s Pro Gen 2", "standard"),
    ("dreame.vacuum.r23646", "L10s Pro Gen 2", "standard"),
    ("dreame.vacuum.r2364a", "L10s Pro Gen 2", "standard"),
    ("dreame.vacuum.r2375", "X30", "standard"),
    ("dreame.vacuum.r2380", "M1", "standard"),
    ("dreame.vacuum.r2380r", "M1", "standard"),
    ("dreame.vacuum.r2382a", "S10", "standard"),
    ("dreame.vacuum.r2382k", "S10", "standard"),
    ("dreame.vacuum.r2382r", "S10", "standard"),
    ("dreame.vacuum.r2385", "G20 Pro", "standard"),
    ("dreame.vacuum.r2386", "免洗10", "standard"),
    ("dreame.vacuum.r2388", "10 Robot Vacuum and Mop", "standard"),
    ("dreame.vacuum.r2412", "S30 Pro", "standard"),
    ("dreame.vacuum.r2416", "X40 Pro", "standard"),
    ("dreame.vacuum.r24162", "GoVac 508", "standard"),
    ("dreame.vacuum.r2421", "S10 Pro (Hot Water)", "standard"),
    ("dreame.vacuum.r2422", "D9 Max Gen 2", "standard"),
    ("dreame.vacuum.r2422a", "D9 Max Gen 2", "standard"),
    ("dreame.vacuum.r2422b", "D9 Max Gen 2 SE", "standard"),
    ("dreame.vacuum.r2422c", "GoVac 100 Lite", "standard"),
    ("dreame.vacuum.r2426", "X40", "standard"),
    ("dreame.vacuum.r2432", "V30", "standard"),
    ("dreame.vacuum.r2435", "G30", "standard"),
    ("dreame.vacuum.r2438a", "E10", "standard"),
    ("dreame.vacuum.r2438b", "E10", "standard"),
    ("dreame.vacuum.r2438i", "E10", "standard"),
    ("dreame.vacuum.r2438r", "E10", "standard"),
    ("dreame.vacuum.r2440", "X40 Pro", "standard"),
    ("dreame.vacuum.r2443", "X40 (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r2455", "G30 Pro", "standard"),
    ("dreame.vacuum.r2458a", "E20", "standard"),
    ("dreame.vacuum.r2458h", "E20", "standard"),
    ("dreame.vacuum.r2462", "P10s Pro", "standard"),
    ("dreame.vacuum.r2467", "X40", "standard"),
    ("dreame.vacuum.r2471", "L10 Prime", "standard"),
    ("dreame.vacuum.r2473", "X40 Pro (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r2478r", "E20 Pro", "standard"),
    ("dreame.vacuum.r2478v", "E20 Pro", "standard"),
    ("dreame.vacuum.r2485", "S30 (Platinum Edition)", "standard"),
    ("dreame.vacuum.r2487", "S40 Pro", "standard"),
    ("dreame.vacuum.r2488", "X30s Pro", "standard"),
    ("dreame.vacuum.r2489", "X50 Pro", "standard"),
    ("dreame.vacuum.r2489d", "GoVac 800", "x50"),
    ("dreame.vacuum.r2508", "S50 Pro", "standard"),
    ("dreame.vacuum.r2515", "X50 Pro (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r2553", "S40", "standard"),
    ("dreame.vacuum.r2562s", "GoVac 400", "standard"),
    ("dreame.vacuum.r2563b", "D20", "standard"),
    ("dreame.vacuum.r2563v", "D20", "standard"),
    ("dreame.vacuum.r25642", "GoVac 300 Kit", "standard"),
    ("dreame.vacuum.r2564s", "GoVac 300", "standard"),
    ("dreame.vacuum.r2565a", "D20 Pro", "standard"),
    ("dreame.vacuum.r2565v", "D20 Pro", "standard"),
    ("dreame.vacuum.r2571", "X40 (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r2573", "S40 (Platinum Edition)", "standard"),
    ("dreame.vacuum.r2575", "S40 (Premium Edition)", "standard"),
    ("dreame.vacuum.r25799", "GoVac 500", "standard"),
    ("dreame.vacuum.r25856", "X50 Pro (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r500a", "S40 Member (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r500n", "S60 Disk", "standard"),
    ("dreame.vacuum.r5016", "澄净 Pro", "standard"),
    ("dreame.vacuum.r5021s", "GoVac 400", "standard"),
    ("dreame.vacuum.r5039", "S50 Max", "standard"),
    ("dreame.vacuum.r50391", "S50 Max-D", "standard"),
    ("dreame.vacuum.r50395", "S50 (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r5082a", "Matrix10 Pro", "standard"),
    ("dreame.vacuum.r5082c", "Matrix10 Pro", "standard"),
    ("dreame.vacuum.r5085", "S50 (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r522kf", "L50s Pro Nano", "standard"),
    ("dreame.vacuum.r5239f", "L50s Pro Nano", "standard"),
    ("dreame.vacuum.r5314s", "GoVac 300", "standard"),
    ("dreame.vacuum.r54125", "D20 Pro", "standard"),
    ("dreame.vacuum.r5412a", "D20 Pro", "standard"),
    ("dreame.vacuum.r5412v", "D20 Pro", "standard"),
    ("dreame.vacuum.r54136", "D20", "standard"),
    ("dreame.vacuum.r5413a", "D20", "standard"),
    ("dreame.vacuum.r5413v", "D20", "standard"),
    ("dreame.vacuum.r6011", "X60 Pro Disc", "standard"),
    ("dreame.vacuum.r6016", "S60 Pro Disc (Water Tank)", "standard"),
    ("dreame.vacuum.r64015", "F21", "standard"),
    ("dreame.vacuum.r6401c", "D20 Air", "standard"),
    ("dreame.vacuum.r6401k", "D20 Air", "standard"),
    ("dreame.vacuum.r6401r", "F20", "standard"),
    ("dreame.vacuum.r6401v", "F20", "standard"),
    ("dreame.vacuum.r9301", "X30 Pro", "standard"),
    ("dreame.vacuum.r9302", "S20 (Mop Pad Swing)", "standard"),
    ("dreame.vacuum.r9311", "S10 Pro (Mop Pad Swing)", "standard"),
    ("dreame.vacuum.r9401", "S40", "standard"),
    ("dreame.vacuum.r9408", "X30s Pro", "standard"),
    ("dreame.vacuum.r9419", "S40 Pro (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r9420", "V30 Pro", "standard"),
    ("dreame.vacuum.r9430", "S40 (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r9455", "X50 Pro (Exclusive Edition)", "standard"),
    ("dreame.vacuum.r9455z", "X50 Pro (Exclusive Edition)", "standard"),
    ("dreame.vacuum.r9461", "X40 Pro (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r9471", "X50", "standard"),
    ("dreame.vacuum.r9471z", "X50", "standard"),
    ("dreame.vacuum.r9476", "X40 (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r9483", "X50 Pro", "standard"),
    ("dreame.vacuum.r9486", "X50 (Pioneer Edition)", "standard"),
    ("dreame.vacuum.r9486z", "X50 (Pioneer Edition)", "standard"),
    ("dreame.vacuum.r9487", "X Series (Clean World Edition)", "standard"),
    ("dreame.vacuum.r9488", "X30s Pro (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r9490", "S40", "standard"),
    ("dreame.vacuum.r9491", "S40 Pro (Enhanced Edition)", "standard"),
    ("dreame.vacuum.r9493c", "GoVac 600", "standard"),
    ("dreame.vacuum.r9517", "S50 Pro", "standard"),
    ("dreame.vacuum.r95239", "F10", "standard"),
    ("dreame.vacuum.r9523a", "F10", "standard"),
    ("dreame.vacuum.r9523b", "GoVac 200 lite", "standard"),
    ("dreame.vacuum.r9523c", "D15", "standard"),
    ("dreame.vacuum.r9523h", "F10", "standard"),
    ("dreame.vacuum.r9523k", "D15", "standard"),
    ("dreame.vacuum.r9523t", "F10", "standard"),
    ("dreame.vacuum.r9523u", "F10", "standard"),
    ("dreame.vacuum.r95249", "GoVac 200 Kit", "standard"),
    ("dreame.vacuum.r9524b", "GoVac 200", "standard"),
    ("dreame.vacuum.r95265", "F21", "standard"),
    ("dreame.vacuum.r95266", "F21", "standard"),
    ("dreame.vacuum.r95267", "F20 Eco", "standard"),
    ("dreame.vacuum.r9526a", "F20", "standard"),
    ("dreame.vacuum.r9526c", "D20 Air", "standard"),
    ("dreame.vacuum.r9526h", "F20", "standard"),
    ("dreame.vacuum.r9526k", "D20 Air", "standard"),
    ("dreame.vacuum.r95385", "GoVac 800", "x50"),
    ("dreame.vacuum.r95425", "L40", "standard"),
    ("dreame.vacuum.r9542a", "L40", "standard"),
    ("dreame.vacuum.r9542b", "L10s Pro Gen3", "standard"),
    ("dreame.vacuum.r9542h", "L10s Pro Gen 3", "standard"),
    ("dreame.vacuum.r9542t", "L20s Pro", "standard"),
    ("dreame.vacuum.r9548", "S50", "standard"),
    ("ijai.vacuum.v1", "Vacuum-Mop Pro", "standard"),
    ("ijai.vacuum.v10", "Vacuum-Mop 2 Lite", "standard"),
    ("ijai.vacuum.v13", "Vacuum-Mop 2 Pro", "standard"),
    ("ijai.vacuum.v14", "M1", "standard"),
    ("ijai.vacuum.v15", "Vacuum-Mop 2 Pro", "standard"),
    ("ijai.vacuum.v16", "Vacuum-Mop 2i", "standard"),
    ("ijai.vacuum.v17", "S10", "standard"),
    ("ijai.vacuum.v18", "3C", "standard"),
    ("ijai.vacuum.v19", "Vacuum-Mop 2S", "standard"),
    ("ijai.vacuum.v2", "Vacuum-Mop 2", "standard"),
    ("ijai.vacuum.v3", "Vacuum-Mop 2 Pro", "standard"),
    ("mova.vacuum.r2430", "Z Series", "standard"),
    ("mova.vacuum.r2533h", "E30 Pro", "standard"),
    ("mova.vacuum.r2569c", "E20s Pro", "standard"),
    ("mova.vacuum.r2570", "N30 Pro", "standard"),
    ("mova.vacuum.r5730", "P60 (Selected Edition)", "standard"),
    ("mova.vacuum.r5766", "Z70 Pro", "standard"),
    ("mova.vacuum.r5769", "P70S (Water Tank Version)", "standard"),
    ("mova.vacuum.r57695", "P70 (Clean World Edition)", "standard"),
    ("mova.vacuum.r58715", "P70 (Clean World Edition)", "standard"),
    ("mova.vacuum.r9427", "P60", "standard"),
    ("mova.vacuum.r9473", "Z60 Pro", "standard"),
    ("mova.vacuum.r9474", "P50 Pro", "standard"),
    ("mova.vacuum.r94745", "P50 (Selected Edition)", "standard"),
    ("mova.vacuum.r9480", "Z Series", "standard"),
    ("mova.vacuum.r9482", "P60 Pro", "standard"),
    ("mova.vacuum.r9503", "Z60 SE", "standard"),
    ("mova.vacuum.r9543", "P70 Pro", "standard"),
    ("szkj.vacuum.fc01eu", "S10T", "standard"),
    ("trouver.vacuum.r2569r", "E20s Pro", "standard"),
    ("xiaomi.vacuum.b106bk", "T12", "standard"),
    ("xiaomi.vacuum.b106eu", "S12", "standard"),
    ("xiaomi.vacuum.b108gl", "S20+", "standard"),
    ("xiaomi.vacuum.b112", "E10", "standard"),
    ("xiaomi.vacuum.b112bk", "E10C", "standard"),
    ("xiaomi.vacuum.b112gl", "E12", "standard"),
    ("xiaomi.vacuum.c101", "人 2", "standard"),
    ("xiaomi.vacuum.c101eu", "X20", "standard"),
    ("xiaomi.vacuum.c102gl", "X20+", "standard"),
    ("xiaomi.vacuum.c103", "3C (Enhanced)", "standard"),
    ("xiaomi.vacuum.c104", "人 3", "standard"),
    ("xiaomi.vacuum.c107", "M30 Pro", "standard"),
    ("xiaomi.vacuum.c108", "E5", "standard"),
    ("xiaomi.vacuum.d101", "H40", "standard"),
    ("xiaomi.vacuum.d102", "M30", "standard"),
    ("xiaomi.vacuum.d102cn", "M30", "standard"),
    ("xiaomi.vacuum.d102ev", "M30", "standard"),
    ("xiaomi.vacuum.d102gl", "X20 Pro", "standard"),
    ("xiaomi.vacuum.d106gl", "S20", "standard"),
    ("xiaomi.vacuum.d109gl", "X20 Max", "standard"),
    ("xiaomi.vacuum.d110ch", "M40", "standard"),
    ("xiaomi.vacuum.ov31cn", "M40 S", "standard"),
    ("xiaomi.vacuum.ov51gl", "H40", "standard"),
    ("dreame.vacuum.p2148o", "Mop Ultra Slim", "wash_station"),
    ("dreame.vacuum.p2150a", "Mi Robot Vacuum-Mop 2 Ultra", "wash_station"),
    ("dreame.vacuum.p2150b", "Mi Robot Vacuum-Mop 2 Ultra Set", "wash_station"),
    ("dreame.vacuum.r2212", "G20 Master", "wash_station"),
    ("dreame.vacuum.r2228d", "L10s Ultra", "wash_station"),
    ("dreame.vacuum.r2228o", "L10s Ultra", "wash_station"),
    ("dreame.vacuum.r2228z", "L10s Ultra", "wash_station"),
    ("dreame.vacuum.r2235", "X10 Ultra", "wash_station"),
    ("dreame.vacuum.r2257o", "L10 Ultra", "wash_station"),
    ("dreame.vacuum.r2310", "Master Pro", "wash_station"),
    ("dreame.vacuum.r2310a", "Master One", "wash_station"),
    ("dreame.vacuum.r2310b", "S10 Pro Ultra (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2310d", "S30 Pro Ultra (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2310e", "X40 Pro (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2310f", "S20 Pro (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2310g", "X30 Pro (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2338a", "L10s Pro Ultra Heat", "wash_station"),
    ("dreame.vacuum.r2338h", "L10S Pro Ultra Heat", "wash_station"),
    ("dreame.vacuum.r2345h", "W20 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2361a", "L30 Ultra", "wash_station"),
    ("dreame.vacuum.r2367", "L10s Ultra Heat", "wash_station"),
    ("dreame.vacuum.r2377", "L10s Pro Ultra Heat", "wash_station"),
    ("dreame.vacuum.r2385a", "S20 Ultra", "wash_station"),
    ("dreame.vacuum.r2401", "X40 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2401a", "X40 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2401h", "X40 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2401u", "X40 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2424", "S30 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2427", "E30 Ultra", "wash_station"),
    ("dreame.vacuum.r2427a", "E30 Ultra", "wash_station"),
    ("dreame.vacuum.r2427c", "E30 Ultra", "wash_station"),
    ("dreame.vacuum.r2427r", "E30 Ultra", "wash_station"),
    ("dreame.vacuum.r2437", "S30 Pro Ultra Gen 2", "wash_station"),
    ("dreame.vacuum.r2441", "S30 Ultra Member (Water Tank Version)", "wash_station"),
    ("dreame.vacuum.r2450m", "X30 Master", "wash_station"),
    ("dreame.vacuum.r2465a", "X40 Master", "wash_station"),
    ("dreame.vacuum.r2465b", "X40 Master", "wash_station"),
    ("dreame.vacuum.r2465h", "X40 Master", "wash_station"),
    ("dreame.vacuum.r2473s", "X40 Pro (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2491", "P10s Ultra", "wash_station"),
    ("dreame.vacuum.r2492a", "L40 Ultra", "wash_station"),
    ("dreame.vacuum.r2492b", "L40 Ultra", "wash_station"),
    ("dreame.vacuum.r2492j", "L40 Ultra", "wash_station"),
    ("dreame.vacuum.r2495", "X40 Pro Ultra (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2501", "X50 Ultra (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2501l", "X50 Pro Master", "wash_station"),
    ("dreame.vacuum.r2501p", "X50s Pro Master", "wash_station"),
    ("dreame.vacuum.r2502", "X50 Pro (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2504", "S30 Pro Ultra (Selected Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2505", "X50 (Pioneer Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2505z", "X50 (Pioneer Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2507", "S50 Ultra", "wash_station"),
    ("dreame.vacuum.r2513", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r25135", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r2513a", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r2513f", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r2513h", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r2513k", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r2513p", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r2513u", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r2518", "X50 Ultra (Enhanced Edition)", "wash_station"),
    ("dreame.vacuum.r2518a", "X50 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2518f", "X50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2518j", "X50 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2518p", "X50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r2520", "S30 Pro Ultra (Platinum Edition)", "wash_station"),
    ("dreame.vacuum.r2531", "S30 Pro Ultra (Refreshed Edition)", "wash_station"),
    ("dreame.vacuum.r2548", "S50 Ultra (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r25513", "GoVac 510 Complete", "wash_station"),
    ("dreame.vacuum.r2551a", "L40s Ultra", "l40s_ultra"),
    ("dreame.vacuum.r2551h", "L40s Ultra", "l40s_ultra"),
    ("dreame.vacuum.r2560", "X50 Pro (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2562a", "L40 Ultra CE", "wash_station"),
    ("dreame.vacuum.r2562b", "L40 Ultra CE", "wash_station"),
    ("dreame.vacuum.r2562c", "L40s Ultra CE", "wash_station"),
    ("dreame.vacuum.r2562h", "D20 Ultra", "wash_station"),
    ("dreame.vacuum.r2562k", "L40s Ultra CE", "wash_station"),
    ("dreame.vacuum.r2562t", "L10s Ultra CE", "wash_station"),
    ("dreame.vacuum.r2562u", "GoVac 400 Complete", "wash_station"),
    ("dreame.vacuum.r2572", "X40 Pro (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2574", "S40 (Platinum Ultra-thin embedded)", "wash_station"),
    ("dreame.vacuum.r2576", "S40 (Premium Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r2579a", "L40 Ultra AE", "wash_station"),
    ("dreame.vacuum.r2579c", "L40s Ultra AE", "wash_station"),
    ("dreame.vacuum.r2579h", "L40 Ultra AE", "wash_station"),
    ("dreame.vacuum.r2579k", "L40s Ultra AE", "wash_station"),
    ("dreame.vacuum.r2584g", "L30 Ultra S", "wash_station"),
    ("dreame.vacuum.r25857", "X50 Pro (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r500xb", "L10s Ultra Heat", "wash_station"),
    ("dreame.vacuum.r500yb", "D30 Ultra CE", "wash_station"),
    ("dreame.vacuum.r500yc", "D30 Ultra CE", "wash_station"),
    ("dreame.vacuum.r500ye", "D30 Ultra CE", "wash_station"),
    ("dreame.vacuum.r500yt", "D30 Ultra CE", "wash_station"),
    ("dreame.vacuum.r500za", "L40 Ultra AE", "wash_station"),
    ("dreame.vacuum.r500zc", "L40s Ultra AE", "wash_station"),
    ("dreame.vacuum.r500zh", "L40 Ultra AE", "wash_station"),
    ("dreame.vacuum.r500zk", "L40s Ultra AE", "wash_station"),
    ("dreame.vacuum.r501da", "L60 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r501h", "L10s Ultra Gen 3", "l50"),
    ("dreame.vacuum.r501he", "L10s Ultra Gen 3", "l50"),
    ("dreame.vacuum.r501st", "L30s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r501t", "L40 Ultra Gen 2", "l50"),
    ("dreame.vacuum.r501tt", "L10s Ultra Gen 3", "l50"),
    ("dreame.vacuum.r501vr", "L60 Ultra AE", "wash_station"),
    ("dreame.vacuum.r501w", "X60 Master (Ultimate edition)", "wash_station"),
    ("dreame.vacuum.r5021a", "L40 Ultra CE", "wash_station"),
    ("dreame.vacuum.r5021b", "L40 Ultra CE", "wash_station"),
    ("dreame.vacuum.r5021c", "L40s Ultra CE", "wash_station"),
    ("dreame.vacuum.r5021h", "L40 Ultra CE", "wash_station"),
    ("dreame.vacuum.r5021k", "L10s Ultra CE", "wash_station"),
    ("dreame.vacuum.r5021t", "L10s Ultra CE", "wash_station"),
    ("dreame.vacuum.r5021u", "GoVac 400 Complete", "wash_station"),
    ("dreame.vacuum.r5022a", "D20 Ultra", "wash_station"),
    ("dreame.vacuum.r5023a", "L10s Ultra Gen 3", "l50"),
    ("dreame.vacuum.r5023e", "L10s Ultra Gen 3", "l50"),
    ("dreame.vacuum.r5024t", "L30s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r5025b", "L10s Ultra Gen 3", "l50"),
    ("dreame.vacuum.r5025t", "L10s Ultra Gen 3", "l50"),
    ("dreame.vacuum.r502ca", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r502k3", "L50s Ultra", "wash_station"),
    ("dreame.vacuum.r502ka", "L50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r502ke", "L50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r50393", "L50s Ultra", "wash_station"),
    ("dreame.vacuum.r50397", "L60 Ultra PE", "l60_ultra_pe"),
    ("dreame.vacuum.r50398", "L60 Ultra PE", "l60_ultra_pe"),
    ("dreame.vacuum.r50399", "L50s Ultra", "wash_station"),
    ("dreame.vacuum.r5039a", "L50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r5039e", "L50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r5039f", "L50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r5039h", "L50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r5039r", "L50s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r5039w", "L50s Pro Ultra Complete", "wash_station"),
    ("dreame.vacuum.r50573", "D30 Ultra", "d30_ultra"),
    ("dreame.vacuum.r5057a", "L40 Ultra A", "d30_ultra"),
    ("dreame.vacuum.r5057k", "D30 Ultra", "d30_ultra"),
    ("dreame.vacuum.r5057r", "D30 Ultra", "d30_ultra"),
    ("dreame.vacuum.r50625", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r5062a", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r5062h", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r5062k", "Matrix10 Ultra", "matrix10"),
    ("dreame.vacuum.r50855", "M50 Ultra", "wash_station"),
    ("dreame.vacuum.r5090a", "L60 Ultra", "l60_ultra"),
    ("dreame.vacuum.r5104h", "X60 Master", "wash_station"),
    ("dreame.vacuum.r510a", "S40 Member (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r510b1", "S60 Pro (Automatic Water Supply and Drainage)", "wash_station"),
    ("dreame.vacuum.r510n", "S60 (Automatic Water Supply and Drainage)", "wash_station"),
    ("dreame.vacuum.r5117", "澄净 Pro (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r512g", "X60 Master (Ultimate Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r5139", "S50 Max (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r51395", "S50 (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r5149", "X50 Plus (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r5185", "S50 (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r51855", "M50 Ultra (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r5189j", "X60 Master", "wash_station"),
    ("dreame.vacuum.r5189u", "X60 Master", "wash_station"),
    ("dreame.vacuum.r520b1", "S60 Pro (Automatic Water Supply and Drainage)", "wash_station"),
    ("dreame.vacuum.r520n", "S60 (Automatic Water Supply and Drainage)", "wash_station"),
    ("dreame.vacuum.r6012", "Clean Master X60 Pro Steam", "wash_station"),
    ("dreame.vacuum.r6015a", "L60 Ultra", "l60_ultra"),
    ("dreame.vacuum.r6111", "X60 Pro Disc (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r6112", "Clean Master X60 Pro Steam (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r6116", "S60 Pro Disc (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r6216", "S60 Pro Disc (Automatic Water Supply and Drainage)", "wash_station"),
    ("dreame.vacuum.r9304", "S10 Pro Ultra (Mop Pad Swing)", "wash_station"),
    ("dreame.vacuum.r9309a", "L10s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9316a", "X30 Ultra", "wash_station"),
    ("dreame.vacuum.r9316h", "X30 Ultra", "wash_station"),
    ("dreame.vacuum.r9316k", "X30 Ultra", "wash_station"),
    ("dreame.vacuum.r9317a", "L30 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9406", "P10 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9419a", "L40s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9419e", "L40s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9419h", "L40s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9419t", "L40s Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9421", "L30s Ultra", "wash_station"),
    ("dreame.vacuum.r9421t", "L30s Ultra", "wash_station"),
    ("dreame.vacuum.r9422", "X40 (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9425", "S30 Pro Ultra (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9426", "S40 (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9426x", "S40 Pro (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9428", "S40 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9434", "X50 Pro (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r94345", "X50 Master", "wash_station"),
    ("dreame.vacuum.r94346", "X50 Master", "wash_station"),
    ("dreame.vacuum.r9434h", "X50 Master", "wash_station"),
    ("dreame.vacuum.r9434j", "X50 Master", "wash_station"),
    ("dreame.vacuum.r9434l", "X50 Master", "wash_station"),
    ("dreame.vacuum.r9434v", "X50 Master", "wash_station"),
    ("dreame.vacuum.r9441", "S30 Pro Ultra (Enhanced Edition)", "wash_station"),
    ("dreame.vacuum.r9445a", "L50 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9445d", "L50 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9445g", "L50 Pro Ultra", "wash_station"),
    ("dreame.vacuum.r9477", "S30 Pro Ultra (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9478", "S30 Ultra Member (Water Tank Version)", "wash_station"),
    ("dreame.vacuum.r9479", "S30 Pro Ultra (Enhanced Edition)", "wash_station"),
    ("dreame.vacuum.r9489", "S40 Pro (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9498", "S30 Pro Ultra (Selected Edition)", "wash_station"),
    ("dreame.vacuum.r9506", "S50 Pro (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9507b", "D20 Ultra", "wash_station"),
    ("dreame.vacuum.r9508b", "X50 Pro Ultra Complete", "wash_station"),
    ("dreame.vacuum.r9513", "X50 Pro (Enhanced Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9516", "S50 Ultra", "wash_station"),
    ("dreame.vacuum.r9518", "S50 Ultra (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9519", "S50 Pro (Ultra-Thin embedded)", "wash_station"),
    ("dreame.vacuum.r9551", "S50 (Ultra-Thin embedded)", "wash_station"),
    ("mova.vacuum.r2430a", "Z50 Ultra", "wash_station"),
    ("mova.vacuum.r2430u", "Z50 Ultra", "wash_station"),
    ("mova.vacuum.r2432b", "P20 Ultra", "wash_station"),
    ("mova.vacuum.r2462a", "P10 Ultra", "wash_station"),
    ("mova.vacuum.r2475a", "P50 Pro Ultra", "wash_station"),
    ("mova.vacuum.r2475h", "P50 Pro Ultra", "wash_station"),
    ("mova.vacuum.r2475t", "P50 Pro Ultra", "wash_station"),
    ("mova.vacuum.r2491a", "P10 Pro Ultra", "wash_station"),
    ("mova.vacuum.r2519a", "P50 Ultra", "wash_station"),
    ("mova.vacuum.r2525a", "V50 Ultra", "wash_station"),
    ("mova.vacuum.r2525e", "V50 Ultra", "wash_station"),
    ("mova.vacuum.r2525h", "V50 Ultra", "wash_station"),
    ("mova.vacuum.r2535", "P60 Pro (Automatic Water Supply and Drainage)", "wash_station"),
    ("mova.vacuum.r2561", "Z60 Pro (Automatic Water Supply and Drainage)", "wash_station"),
    ("mova.vacuum.r2582a", "V50 Ultra complete", "wash_station"),
    ("mova.vacuum.r2582c", "V50 Ultra Complete", "wash_station"),
    ("mova.vacuum.r2582h", "V50 Ultra complete", "wash_station"),
    ("mova.vacuum.r2582k", "V50 Ultra Complete", "wash_station"),
    ("mova.vacuum.r2587a", "P50 Pro Ultra", "wash_station"),
    ("mova.vacuum.r5730c", "P10 Pro Ultra Gen 2", "wash_station"),
    ("mova.vacuum.r5732a", "E40 Ultra", "wash_station"),
    ("mova.vacuum.r5747", "P60 (Selected Automatic Water Supply and Drainage)", "wash_station"),
    ("mova.vacuum.r5770", "P70 Pro Ultra", "wash_station"),
    ("mova.vacuum.r590q", "P70 Pro Ultra", "wash_station"),
    ("mova.vacuum.r5977a", "P70 Pro Ultra", "wash_station"),
    ("mova.vacuum.r5977c", "P70 Pro Ultra", "wash_station"),
    ("mova.vacuum.r5977f", "P70 Pro Ultra", "wash_station"),
    ("mova.vacuum.r5977g", "P70 Pro Ultra", "wash_station"),
    ("mova.vacuum.r5977h", "P70 Pro Ultra", "wash_station"),
    ("mova.vacuum.r5977k", "P70 Pro Ultra", "wash_station"),
    ("mova.vacuum.r59795", "V70 Ultra Complete X", "wash_station"),
    ("mova.vacuum.r59796", "V70 Ultra Complete X", "wash_station"),
    ("mova.vacuum.r59799", "V70 Ultra Complete X", "wash_station"),
    ("mova.vacuum.r5979a", "V70 Ultra Complete", "wash_station"),
    ("mova.vacuum.r5979h", "V70 Ultra Complete", "wash_station"),
    ("mova.vacuum.r67095", "E50 Ultra", "wash_station"),
    ("mova.vacuum.r6709a", "E50 Ultra", "wash_station"),
    ("mova.vacuum.r6709c", "P20 Ultra", "wash_station"),
    ("mova.vacuum.r6709h", "E50 Ultra", "wash_station"),
    ("mova.vacuum.r6710a", "E50 Pro Ultra", "wash_station"),
    ("mova.vacuum.r9416", "P50 (Automatic Water Supply and Drainage)", "wash_station"),
    ("mova.vacuum.r94165", "P50 (Selected Automatic Water Supply and Drainage)", "wash_station"),
    ("mova.vacuum.r9416d", "P50 Pro Ultra", "wash_station"),
    ("mova.vacuum.r9427h", "P50s Ultra", "wash_station"),
    ("mova.vacuum.r95046", "E30 Pro Ultra", "wash_station"),
    ("mova.vacuum.r95049", "E30 Pro Ultra Complete", "wash_station"),
    ("mova.vacuum.r9504a", "E40 Ultra", "wash_station"),
    ("trouver.vacuum.2430v", "Z50 Ultra", "wash_station"),
    ("trouver.vacuum.r2461r", "E30 Aqua", "wash_station"),
    ("trouver.vacuum.r2475r", "P50 Pro Ultra", "wash_station"),
    ("trouver.vacuum.r2519r", "P50 Ultra", "wash_station"),
    ("trouver.vacuum.r2582r", "V50 Ultra complete", "wash_station"),
    ("trouver.vacuum.r9504r", "E40 Ultra", "wash_station"),
    ("xiaomi.vacuum.c102cn", "Omni 2", "wash_station"),
    ("xiaomi.vacuum.d103cn", "Omni M30S", "wash_station"),
    ("dreame.vacuum.r25858", "S60 Roller", "wash_station_roller"),
    ("dreame.vacuum.r25859", "S60 Roller (Ultra-Thin embedded)", "wash_station_roller"),
    ("dreame.vacuum.r500b", "S60 Pro (Roller)", "wash_station_roller"),
    ("dreame.vacuum.r500b1", "S60 Pro Roller", "wash_station_roller"),
    ("dreame.vacuum.r500c", "X60 Pro (Roller)", "wash_station_roller"),
    ("dreame.vacuum.r500c1", "X60 Pro Roller", "wash_station_roller"),
    ("dreame.vacuum.r501ba", "Aqua10 Roller AE", "wash_station_roller"),
    ("dreame.vacuum.r501bc", "Aqua10 Roller AE", "wash_station_roller"),
    ("dreame.vacuum.r501bk", "Aqua10 Roller AE", "wash_station_roller"),
    ("dreame.vacuum.r501bt", "Aqua 10 Roller", "wash_station_roller"),
    ("dreame.vacuum.r5064t", "Aqua 10 Pro Roller", "wash_station_roller"),
    ("dreame.vacuum.r5064u", "Aqua10 Pro Roller", "wash_station_roller"),
    ("dreame.vacuum.r5099", "S60 Premium Roller", "wash_station_roller"),
    ("dreame.vacuum.r5099a", "Aqua10s Roller AE", "wash_station_roller"),
    ("dreame.vacuum.r5099e", "Aqua10s Roller AE", "wash_station_roller"),
    ("dreame.vacuum.r5099h", "Aqua10s Roller AE", "wash_station_roller"),
    ("dreame.vacuum.r5099k", "Aqua20 Roller FE", "wash_station_roller"),
    ("dreame.vacuum.r510b", "S60 Pro (Roller Drainage)", "wash_station_roller"),
    ("dreame.vacuum.r510c", "X60 Pro (Roller Drainage)", "wash_station_roller"),
    ("dreame.vacuum.r510c1", "X60 Pro Roller (Ultra-Thin embedded)", "wash_station_roller"),
    ("dreame.vacuum.r520b", "S60 Pro (Roller Drainage)", "wash_station_roller"),
    ("dreame.vacuum.r520c", "X60 Pro (Roller Drainage)", "wash_station_roller"),
    ("dreame.vacuum.r520c1", "X60 Pro Roller (Automatic Water Supply and Drainage)", "wash_station_roller"),
    ("dreame.vacuum.r5299", "S60 Premium Roller (Automatic Water Supply and Drainage)", "wash_station_roller"),
    ("dreame.vacuum.r9312", "S10 Pro Ultra (Double Roller Brush)", "wash_station_roller"),
    ("dreame.vacuum.r9533a", "Aqua10 Roller", "wash_station_roller"),
    ("dreame.vacuum.r9533h", "Aqua10 Roller", "wash_station_roller"),
    ("dreame.vacuum.r9533t", "Aqua10 Roller", "wash_station_roller"),
    ("mova.vacuum.r2599", "V60 MOBIUS", "wash_station_roller"),
    ("mova.vacuum.r2599h", "MOBIUS 60", "wash_station_roller"),
    ("mova.vacuum.r2599k", "MOBIUS 60", "wash_station_roller"),
    ("mova.vacuum.r2599u", "MOBIUS 60", "wash_station_roller"),
    ("mova.vacuum.r5765h", "Z70 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r5765p", "Z70 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r5765q", "Z70 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r5765u", "Z70 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r5766h", "Z70 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r57698", "S70 Roller Lite", "wash_station_roller"),
    ("mova.vacuum.r5769a", "S70 Roller", "wash_station_roller"),
    ("mova.vacuum.r5769f", "S70 Roller", "wash_station_roller"),
    ("mova.vacuum.r5769g", "S70 Roller", "wash_station_roller"),
    ("mova.vacuum.r5769h", "S70 Roller", "wash_station_roller"),
    ("mova.vacuum.r5769q", "S70 Roller", "wash_station_roller"),
    ("mova.vacuum.r5769t", "S70 Roller", "wash_station_roller"),
    ("mova.vacuum.r5770a", "S70 Ultra Roller", "wash_station_roller"),
    ("mova.vacuum.r5770g", "S70 Ultra Roller", "wash_station_roller"),
    ("mova.vacuum.r5770h", "S70 Ultra Roller", "wash_station_roller"),
    ("mova.vacuum.r5770q", "S70 Ultra Roller", "wash_station_roller"),
    ("mova.vacuum.r5770t", "S70 Ultra Roller", "wash_station_roller"),
    ("mova.vacuum.r5871", "P70S (Automatic Water Supply and Drainage)", "wash_station_roller"),
    ("mova.vacuum.r590qf", "S70 Ultra Roller", "wash_station_roller"),
    ("mova.vacuum.r9427x", "P60 (Automatic Water Supply and Drainage)", "wash_station_roller"),
    ("mova.vacuum.r9473e", "Z60 Ultra Roller", "wash_station_roller"),
    ("mova.vacuum.r9540a", "Z60 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r9540h", "Z60 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r9540k", "Z60 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r9540n", "Z60 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r9540u", "Z60 Ultra Roller Complete", "wash_station_roller"),
    ("mova.vacuum.r9543a", "Z70 Ultra Roller SE", "wash_station_roller"),
    ("mova.vacuum.r9543b", "S70 Pro Roller", "wash_station_roller"),
    ("mova.vacuum.r9544a", "Z60 Ultra Roller Standalone", "wash_station_roller"),
    ("mova.vacuum.r9544b", "Z60 Ultra Roller SA", "wash_station_roller"),
    ("mova.vacuum.r9544t", "Z60 Roller", "wash_station_roller"),
    ("mova.vacuum.r9549", "P70 Pro (Automatic Water Supply and Drainage)", "wash_station_roller"),
    ("trouver.vacuum.r2599v", "MOBIUS 60", "wash_station_roller"),
    ("trouver.vacuum.r5769r", "S70 Roller", "wash_station_roller"),
    ("trouver.vacuum.r5770v", "S70 Ultra Roller", "wash_station_roller"),
    ("trouver.vacuum.r9540v", "Z60 Ultra Roller Complete", "wash_station_roller"),
    ("trouver.vacuum.r9543r", "S70 Pro Roller", "wash_station_roller"),
    ("dreame.vacuum.r2527", "X50 Ultra (Tracked Version)", "wash_station_track"),
    ("dreame.vacuum.r2527b", "Aqua 10 Pro Track", "aqua10_ultra_track"),
    ("dreame.vacuum.r2527j", "Aqua 10 Pro Track", "aqua10_ultra_track"),
    ("dreame.vacuum.r2527t", "Aqua 10 Pro Track", "aqua10_ultra_track"),
    ("dreame.vacuum.r2527u", "Aqua 10 Pro Track", "aqua10_ultra_track"),
    ("dreame.vacuum.r2580", "X50 Pro (Tracked Version)", "wash_station_track"),
    ("dreame.vacuum.r2581", "X50 (Tracked Version)", "wash_station_track"),
    ("dreame.vacuum.r501wu", "X60 Track", "wash_station_track"),
    ("dreame.vacuum.r2416a", "X40 Ultra", "x40"),
    ("dreame.vacuum.r2416c", "X40 Ultra", "x40"),
    ("dreame.vacuum.r2416f", "X40 Ultra", "x40"),
    ("dreame.vacuum.r2416h", "X40 Ultra", "x40"),
    ("dreame.vacuum.r2416n", "X40 Ultra", "x40"),
    ("dreame.vacuum.r24495", "X40 Ultra Complete", "x40"),
    ("dreame.vacuum.r2449a", "X40 Ultra Complete", "x40"),
    ("dreame.vacuum.r2449b", "X40 Ultra Complete", "x40"),
    ("dreame.vacuum.r2449k", "X40 Ultra Complete", "x40"),
    ("dreame.vacuum.r24896", "X50 Ultra", "x50"),
    ("dreame.vacuum.r24898", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489a", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489b", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489c", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489e", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489f", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489h", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489j", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489k", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489l", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489p", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489q", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489s", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489t", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489u", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2489z", "X50 Ultra", "x50"),
    ("dreame.vacuum.r2532a", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r2532d", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r2532h", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r2532v", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r2532w", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r2532z", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r2538a", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r2538z", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r50485", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r5048a", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r5048h", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r9446a", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r9446c", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r9446h", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r9446k", "X50 Ultra Complete", "x50"),
    ("dreame.vacuum.r9538a", "X50 Ultra", "x50"),
    ("dreame.vacuum.r9538b", "X50 Ultra", "x50"),
    ("dreame.vacuum.r9538c", "X50 Ultra", "x50"),
    ("dreame.vacuum.r9538e", "X50 Ultra", "x50"),
    ("dreame.vacuum.r9538h", "X50 Ultra", "x50"),
    ("dreame.vacuum.r9538k", "X50 Ultra", "x50"),
    ("dreame.vacuum.r9538l", "X50 Ultra", "x50"),
    ("dreame.vacuum.r9538t", "X50 Ultra", "x50"),
    ("dreame.vacuum.r9538u", "X50 Ultra", "x50"),
    ("dreame.vacuum.r6001a", "X60 Pro Ultra Complete", "x60_pro_ultra_complete"),
    ("dreame.vacuum.r5089b", "X60 Ultra", "x60_ultra"),
    ("dreame.vacuum.r5089u", "X60 Ultra", "x60_ultra"),
    ("dreame.vacuum.r9515a", "X60 Ultra", "x60_ultra"),
    ("dreame.vacuum.r9515e", "X60 Ultra", "x60_ultra"),
]

DREAME_MODEL_NAMES: dict[str, str] = {m: n for m, n, _ in DREAME_MODELS}
DREAME_MODEL_GUIDE_FAMILIES: dict[str, str] = {m: f for m, n, f in DREAME_MODELS}
DREAME_GUIDE_FAMILY_NAMES: dict[str, str] = {
    "standard": "Standard",
    "auto_empty": "Auto-Empty Dock",
    "wash_station": "Wash Station",
    "wash_station_track": "Wash Station (Tracked Mop)",
    "wash_station_roller": "Wash Station (Roller Mop)",
    "wash_station_baseboard": "Wash Station (Baseboard Brush)",
    "x50": "X50 Ultra",
    "x60_ultra": "X60 Ultra",
    "x60_pro_ultra_complete": "X60 Pro Ultra Complete",
    "l20": "L20 Ultra",
    "x40": "X40 Ultra",
    "l50": "L50 Ultra",
    "l10s_gen2": "L10s Ultra Gen 2",
    "aqua10_ultra_track": "Aqua10 Ultra Track",
    "aqua10_ultra_roller": "Aqua10 Ultra Roller",
    # --- overnight batch 2026-08-31 ---
    'matrix10': 'Matrix10 Ultra',
    'l60_ultra': 'L60 Ultra',
    'l60_ultra_pe': 'L60 Ultra PE',
    'l40s_ultra': 'L40s Ultra',
    'd30_ultra': 'D30 Ultra',
    'd20_pro_plus': 'D20 Pro Plus',
    'd20_plus': 'D20 Plus',
}
