#!/usr/bin/env node
/**
 * Preview theme EXPORTS (the export/import schema) by running each through the
 * ingest gate and rendering the REAL card with it — the same harness render,
 * recolored by the uploaded theme. Scope drives output:
 *   full theme     -> contact sheet of the all-states galleries
 *   texture-scoped  -> the rooms gallery (where floor textures live)
 *
 *   node harness/preview.mjs [path/to/export.json]   # one export
 *   node harness/preview.mjs                          # scans gallery/themes/*.json
 *
 * Output: harness/out/preview/<name>/  (PNGs + ingest-report.json) plus a
 * self-contained index.html gallery — that directory is what the
 * theme-intake workflow publishes to GitHub Pages.
 *
 * The ingest gate (window.__evcc.ingestTheme) makes this safe on untrusted
 * uploads: malformed/unknown-namespace exports are skipped, every value is
 * clamped, nothing is eval'd.
 */
import { chromium } from "@playwright/test";
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, basename } from "node:path";
import { mountHarness } from "./lib/mount-page.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");
const OUT = join(repo, "harness", "out", "preview");
const FULL_GALLERIES = ["rooms-active", "review-badges", "mapping-badges"];

function exportsToProcess() {
  const arg = process.argv[2];
  if (arg && arg.trim()) return [arg.trim()];
  const dir = join(repo, "gallery", "themes");
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((f) => f.endsWith(".json")).map((f) => join(dir, f));
}

const esc = (s) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

/** Write a self-contained static gallery index over the rendered themes. */
function writeIndex(entries) {
  const cards = entries
    .map((e) => {
      const dir = encodeURIComponent(e.name);
      const meta = `scope: ${e.scope.length ? esc(e.scope.join(", ")) : "full"} · ` +
        `${e.report.keyCount} tokens · ${e.report.clamped} clamped · ${e.report.skippedKeys.length} skipped`;
      return `      <article class="card">
        <h2>${esc(e.themeName)}</h2>
        <p class="meta">${meta}</p>
        <a href="${dir}/_contact-sheet.png"><img loading="lazy" src="${dir}/_contact-sheet.png" alt="${esc(e.themeName)} preview"></a>
        <p class="links"><a href="${dir}/ingest-report.json">ingest report</a></p>
      </article>`;
    })
    .join("\n");

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>EVCC theme gallery</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; background: #0b0d10; color: #e6e9ee; font: 15px/1.5 system-ui, -apple-system, sans-serif; }
  header { padding: 28px 24px 8px; }
  header h1 { margin: 0 0 4px; font-size: 1.4rem; }
  header p { margin: 0; color: #99a2ad; }
  main { display: grid; grid-template-columns: repeat(auto-fill, minmax(420px, 1fr)); gap: 20px; padding: 20px 24px 40px; }
  .card { background: #14181d; border: 1px solid #232a32; border-radius: 12px; padding: 14px 14px 10px; }
  .card h2 { margin: 0 0 2px; font-size: 1.05rem; }
  .meta { margin: 0 0 10px; color: #8b94a0; font-size: 0.82rem; }
  .card img { display: block; width: 100%; height: auto; border-radius: 8px; border: 1px solid #232a32; background: #0b0d10; }
  .links { margin: 8px 0 0; font-size: 0.8rem; }
  .links a, header a { color: #5aa9ff; }
  footer { padding: 0 24px 36px; color: #6b7480; font-size: 0.8rem; }
  footer code { color: #99a2ad; }
</style>
</head>
<body>
  <header>
    <h1>EVCC theme gallery</h1>
    <p>${entries.length} theme${entries.length === 1 ? "" : "s"} rendered through the harness ingest gate — each is the real card recolored by a committed export.</p>
  </header>
  <main>
${cards}
  </main>
  <footer>Generated by <code>harness/preview.mjs</code>. Add a theme by committing its export to <code>gallery/themes/</code>.</footer>
</body>
</html>
`;
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, "index.html"), html);
}

const files = exportsToProcess();
if (!files.length) {
  console.log("no theme exports to preview (looked in gallery/themes/)");
  process.exit(0);
}

const browser = await chromium.launch();
const page = await browser.newPage({ deviceScaleFactor: 2 });
const processed = [];

for (const file of files) {
  const name = basename(file).replace(/\.json$/, "");

  // Read as pure data; a parse failure is a skipped (not rendered) upload.
  let envelope;
  try {
    envelope = JSON.parse(readFileSync(file, "utf8"));
  } catch (e) {
    console.error(`skip ${name}: invalid JSON (${e.message})`);
    continue;
  }

  await mountHarness(page); // (re)load the bundle — contact-sheet setContent below replaces it
  const { bundle, scope, report } = await page.evaluate(
    (env) => window.__evcc.ingestTheme(env),
    envelope,
  );
  if (!report.ok) {
    console.error(`skip ${name}: ${report.reason}`);
    continue;
  }

  const outDir = join(OUT, name);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "ingest-report.json"), JSON.stringify({ scope, ...report }, null, 2));

  // Scope drives what we show.
  const ids = scope.length ? ["rooms-active"] : FULL_GALLERIES;
  const shots = [];
  for (const id of ids) {
    const res = await page.evaluate(
      ([gid, b]) => window.__evcc.renderGallery(gid, { bundle: b, freeze: true, width: 520 }),
      [id, bundle],
    );
    if (!res.ok) {
      console.error(`  ${name}/${id}: ${res.error}`);
      continue;
    }
    const buf = await page.locator("#evcc-host").screenshot();
    writeFileSync(join(outDir, `${id}.png`), buf);
    shots.push({ id, b64: buf.toString("base64") });
  }

  // Per-theme contact sheet (this navigates the page away — we re-mount next iteration).
  const cols = Math.min(shots.length, 3) || 1;
  const cells = shots
    .map(
      (s) => `<figure style="margin:0">
        <figcaption style="font:12px/1.4 system-ui,sans-serif;color:#cbd2da;padding:4px 2px">${s.id}</figcaption>
        <img src="data:image/png;base64,${s.b64}" style="display:block;width:520px;border:1px solid #2a2f37"></figure>`,
    )
    .join("");
  await page.setContent(
    `<body style="margin:0;background:#0b0d10;display:grid;grid-template-columns:repeat(${cols},540px);gap:16px;padding:16px;align-items:start">${cells}</body>`,
    { waitUntil: "domcontentloaded" },
  );
  writeFileSync(join(outDir, "_contact-sheet.png"), await page.screenshot({ fullPage: true }));

  processed.push({ name, themeName: envelope.theme?.name || name, scope, report });
  console.log(
    `✓ ${name}: ${report.keyCount} keys, scope=[${scope.join(",") || "full"}], ` +
      `${report.clamped} clamped, ${report.skippedKeys.length} skipped -> harness/out/preview/${name}/`,
  );
}

if (processed.length) {
  writeIndex(processed);
  console.log(`index -> harness/out/preview/index.html (${processed.length} theme${processed.length === 1 ? "" : "s"})`);
}

await browser.close();
