/**
 * The Pages landing page (site root) — a hub linking to the theme gallery, the
 * animal gallery, and the docs. Generated by harness/build-landing.mjs after the
 * galleries render, so it can show live counts.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { esc, siteNav, SITE_NAV_CSS } from "./site-nav.mjs";

/**
 * @param {string} outDir
 * @param {object} opts { themeCount, animalCount, repoUrl }
 */
export function writeLanding(outDir, { themeCount = 0, animalCount = 0, repoUrl = "https://github.com/kingchddg901/Vacuum_Agent" } = {}) {
  const card = (href, icon, title, blurb, count) => `      <a class="card" href="${href}">
        <span class="card-icon">${icon}</span>
        <h2>${esc(title)}</h2>
        <p>${esc(blurb)}</p>
        ${count != null ? `<span class="count">${count}</span>` : ""}
      </a>`;

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vacuum Agent</title>
<style>
  :root { color-scheme: dark; }
  body { margin:0; background:#0b0d10; color:#e6e9ee; font:15px/1.6 system-ui,-apple-system,sans-serif; }
  .hero { padding:56px 24px 24px; max-width:880px; margin:0 auto; text-align:center; }
  .hero h1 { margin:0 0 8px; font-size:2.2rem; letter-spacing:-0.02em; }
  .hero p { margin:0 auto; color:#99a2ad; max-width:620px; font-size:1.05rem; }
  main { max-width:880px; margin:0 auto; padding:8px 24px 56px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:18px; }
  .card { display:flex; flex-direction:column; gap:6px; position:relative; background:#14181d; border:1px solid #232a32; border-radius:14px; padding:22px 20px; text-decoration:none; color:inherit; transition:border-color .15s, transform .15s; }
  .card:hover { border-color:#2f6dd0; transform:translateY(-2px); }
  .card-icon { font-size:1.9rem; }
  .card h2 { margin:6px 0 0; font-size:1.15rem; }
  .card p { margin:0; color:#99a2ad; font-size:.9rem; }
  .count { position:absolute; top:18px; right:20px; background:#173455; color:#cfe2ff; border-radius:999px; padding:2px 10px; font-size:.78rem; font-weight:600; }
  footer { max-width:880px; margin:0 auto; padding:0 24px 40px; color:#6b7480; font-size:.82rem; text-align:center; }
  footer a { color:#5aa9ff; }
${SITE_NAV_CSS}
</style>
</head>
<body>
  ${siteNav(0, "home")}
  <div class="hero">
    <h1>Vacuum Agent</h1>
    <p>A premium dashboard for Eufy &amp; Roborock robot vacuums in Home Assistant — live maps, per-room cleaning, a theme system, and companion animals on your map.</p>
  </div>
  <main>
    <div class="grid">
${card("themes/", "🎨", "Theme gallery", "Browse and download community card themes — every one is the real card recolored.", themeCount || null)}
${card("animals/", "🦊", "Animal gallery", "Companion animals for your map. Submit your own — or remember a pet in Rainbow Bridge.", animalCount || null)}
${card("docs/", "📖", "Documentation", "User guides, the theme + animal authoring guides, services, and the developer deep-dives.")}
${card(esc(repoUrl), "⚙️", "GitHub", "Source, releases, and the integration itself. Install via HACS.")}
    </div>
  </main>
  <footer>Generated for the Vacuum Agent Pages site · <a href="${esc(repoUrl)}">github.com/kingchddg901/Vacuum_Agent</a></footer>
</body>
</html>
`;
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "index.html"), html);
}
