"""Generate RP-040's per-file member table — the artifact its packet assumes.

RP-040 ("closing batches") references "the generated per-file table" four times:
as its finding list, its expected_before/after source, its superseded_tests
source, and its rollback_plan (commit -> members). The table was never
generated, which left the packet unexecutable: its `finding_ids` are
corpus-record-only labels, so an executor would have had to read the raw audit
corpus — against the standing instruction that the packets are the spec.

This closes that gap WITHOUT relaxing the instruction. Every member resolves to a
prose record already present in the generated indices (`_open_findings.json` +
`_direct_reads.json`), so the table carries the mechanism, file, line and impact
per member and the executor never opens the corpus.

    python .claude/notes/_gen_batch_table.py

Re-runnable. Output: .claude/notes/synthesis/RP-040-batch-table.md
"""
import collections
import glob
import json
import pathlib
import re

N = pathlib.Path(".claude/notes")
OUT = N / "synthesis/RP-040-batch-table.md"

# The four batch owners, and what gates each per the packet.
GATES = {
    "BATCH:SMALL-CORRECTNESS":  "table-driven proof + full suite",
    "BATCH:SMALL-CORRECTNESS-": "table-driven proof + full suite",
    "BATCH:DOC-ONLY":           "mkdocs --strict",
    "BATCH:DEAD-CODE":          "full suite",
}
# Ejected by decision Q20 — belongs to RP-041, must NOT appear here.
EJECTED = {"A6-PRE-1"}

SEVR = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}


def main() -> None:
    cm = json.loads((N / "synthesis/closure-matrix.json").read_text(encoding="utf-8"))
    recs = json.loads((N / "_open_findings.json").read_text(encoding="utf-8"))
    recs += json.loads((N / "_direct_reads.json").read_text(encoding="utf-8"))

    by_id = {}
    for r in recs:
        by_id.setdefault(r["id"], r)
        by_id.setdefault(f"{r.get('run', '')}:{r['id']}", r)

    # THE CROSS-CHECK THAT THE FIRST VERSION OF THIS SCRIPT LACKED.
    # closure-matrix.json's `owner` is STALE: REVIEW-07 moved members out of the
    # batches into named packets ("membership adds") and the matrix was never
    # rewritten. Resolving every id to a prose record proved only that the record
    # EXISTS — not that the batch still owns it. Without this, the table listed 75
    # members of which 42 were already owned by RP-013e/025/029/030/031/034/035/
    # 037/039, and RP-040's executor would have applied one-line batch treatment
    # to findings those packets specify designed fixes for (three HIGH saved-zone
    # items among them). The PACKETS are authoritative; the matrix is a hint.
    claimed: dict[str, list[str]] = {}
    for path in sorted(glob.glob(".claude/notes/synthesis/SYNTH-*.md")):
        text = pathlib.Path(path).read_text(encoding="utf-8")
        for pm in re.finditer(r"packet_id: ([A-Z]+-[0-9a-z]+)(.*?)(?=packet_id:|\Z)",
                              text, re.S):
            pid, body = pm.group(1), pm.group(2)
            if pid == "RP-040":
                continue
            fm = re.search(r"finding[s]?_(?:ids|addressed): \[(.*?)\]", body, re.S)
            if not fm:
                continue
            for fid in re.findall(r'"([^"]+)"', fm.group(1)):
                claimed.setdefault(fid, []).append(pid)

    members, unresolved, ejected, elsewhere = [], [], [], []
    for m in cm:
        owner = m.get("owner")
        if owner not in GATES:
            continue
        if m["finding_id"] in EJECTED:
            ejected.append(m["finding_id"])
            continue
        owners_named = claimed.get(m["canonical_id"]) or claimed.get(m["finding_id"])
        if owners_named:
            elsewhere.append((m["canonical_id"], sorted(set(owners_named))))
            continue
        r = by_id.get(m["canonical_id"]) or by_id.get(m["finding_id"])
        if r is None:
            unresolved.append(m["canonical_id"])
            continue
        members.append({**r, "_owner": owner, "_canon": m["canonical_id"]})

    by_file = collections.defaultdict(list)
    for m in members:
        by_file[m.get("file") or "(no file)"].append(m)

    L = []
    A = L.append
    A("# RP-040 — per-file member table (GENERATED)")
    A("")
    A("**Generated by `.claude/notes/_gen_batch_table.py` — do not hand-edit.**")
    A("Re-run it if the closure matrix or the finding indices change.")
    A("")
    A("This is the artifact RP-040's packet refers to four times and which did not")
    A("exist. It carries the prose mechanism for every batch member, so the")
    A("executor works from here and **never needs to open the audit corpus**.")
    A("")
    A(f"**{len(members)} members across {len(by_file)} files.** "
      f"One focused edit + one focused test each; commits grouped BY FILE "
      f"(the packet's rollback_plan).")
    A("")
    if ejected:
        A(f"> Ejected per Q20 and NOT listed here: {', '.join(sorted(ejected))} "
          f"— relevance-gated blocking is a design, not a one-liner; it belongs "
          f"to RP-041.")
        A("")
    if unresolved:
        A(f"> ⚠ {len(unresolved)} member(s) did not resolve to a prose record: "
          f"{', '.join(unresolved)}. Escalate rather than guessing.")
        A("")
    if elsewhere:
        A(f"> **{len(elsewhere)} matrix members are EXCLUDED — a named packet already")
        A("> owns them.** `closure-matrix.json`'s `owner` is stale: REVIEW-07 moved")
        A("> members into named packets and the matrix was not rewritten. Applying")
        A("> one-line batch treatment to these would collide with a designed fix.")
        A("> The packets are authoritative.")
        A("")
        A("| finding | owned by |")
        A("|---|---|")
        for cid, pids in sorted(elsewhere):
            A(f"| `{cid}` | {', '.join(pids)} |")
        A("")
    A("## Gates by batch")
    A("")
    A("| batch | members | gate |")
    A("|---|---:|---|")
    counts = collections.Counter(m["_owner"] for m in members)
    for owner, gate in GATES.items():
        if counts.get(owner):
            A(f"| `{owner}` | {counts[owner]} | {gate} |")
    A("")
    A("A DOC-ONLY member must not gain a proof case; a DEAD-CODE member's evidence")
    A("is the suite still passing after the deletion. Only behaviour-bearing")
    A("members belong in `_proof_closing_batch.py`.")
    A("")
    A("## Members, grouped by file (= commit grouping)")

    for path in sorted(by_file):
        rows = sorted(by_file[path], key=lambda r: (SEVR.get(r.get("sev"), 9),
                                                    r.get("line") or 0))
        A("")
        A(f"### `{path}` — {len(rows)} member(s)")
        A("")
        for r in rows:
            batch = r["_owner"].replace("BATCH:", "")
            line = f":{r['line']}" if r.get("line") else ""
            A(f"- **{r['_canon']}** · {r.get('sev')} · `{path}{line}` · _{batch}_")
            A(f"  - **What:** {r.get('title', '').strip()}")
            impact = (r.get("impact") or "").strip()
            if impact:
                A(f"  - **Impact:** {impact}")
    A("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT} — {len(members)} members, {len(by_file)} files, "
          f"{len(unresolved)} unresolved, {len(ejected)} ejected")


if __name__ == "__main__":
    main()
