"""Dreame upkeep KEY guides — the guards that can actually go red.

The Dreame adapter is DATA ONLY and deliberately unwired, so none of the adapter
contract suites reach it. Without this file the whole key system could be emptied,
renamed, or silently disconnected from the card and the suite would stay green.

WHAT REPLACED WHAT. Until 2026-09-11 the Dreame guide was ~280 hand-authored prose
families routed per model, guarded by test_dreame_upkeep_guides.py (the DUG series).
It is now 51 i18n KEYS routed by REGIME — three measured fields (mop type, dock tier,
on-board tanks) that all 700 models collapse into SEVEN distinct cards. The backend
ships key lists and no words; the card supplies the sentence in the reader's own
language. That library, its 17 language packs and the DUG suite were DELETED the same
day; they live in git history. Three of the DUG questions were real independently of the
family model and were carried over rather than dropped — see DUK-1, DUK-2 and DUK-6.

THE FAILURE MODE THIS SYSTEM HAS THAT THE OLD ONE DID NOT is a broken JOIN. Prose
travelled with its routing key, so a guide was either present or absent. Here a guide
is three tables that must agree — regimes, key lists, and the component rows that give
a guide somewhere to render — and any two of them can drift while each stays internally
valid. DUK-4, DUK-5 and DUK-7 are that join, one seam each; they are the reason this
file exists, and DUK-4 is written from a real miss (the emitter named a panel
``dust_bin_and_filter`` while the card's component was ``filter``, so the guide resolved
to nothing on a card that looked perfectly healthy).

[DUK-1] No BRAND_REGISTRARS row for Dreame. That row is the release, and it is gated on
        a RELEASED upstream build carrying Tasshack #1707. Inherited from [DUG-1] — it
        is about the switch, not the guides, and this file is now its home.
[DUK-2] Every model routes to a regime the key library actually holds. The old [DUG-8],
        re-expressed: an unrouted regime is a KeyError waiting for the release switch.
[DUK-3] Every component in every regime has at least one step, and every step and note
        is a non-empty string. An emptied component fails here, not on a user's screen.
[DUK-4] THE JOIN TO THE CARD. Every component the key library emits has a row in
        maintenance_components — because the manager iterates THAT table, not the guide
        library. A guide under a component with no row is authored, translated, shipped,
        and invisible.
[DUK-5] The same join from the other side: every declared component is reachable — it
        appears in some regime, or it carries a sensor. A row that is neither is a card
        that can never say anything.
[DUK-6] THE REGIME GATES HARDWARE. A dockless robot gets no washboard and no station
        tanks; a pad robot gets no track mop; every model gets exactly one mop panel.
        The old [DUG-5] — silence beats confident instructions about a part that is not
        there — now derived rather than asserted per family.
[DUK-7] THE JOIN TO THE LANGUAGE PACKS. Every key the backend can emit is in the shipped
        English pack. A key renamed in the emitter without re-running
        scripts/sync-dreame-guide-keys.py renders as its own name on the card.
[DUK-8] The collapse holds: 700 models, 15 regimes, SEVEN distinct cards. A tripwire, not
        a law — if a regime change legitimately splits or merges a card, update the number
        deliberately. It is here because the collapse is the whole argument for the system.
[DUK-9] Every component's steps END on a closer. The closer is the one step that does not
        act on a part: it tells the reader the task is finished and nothing was left
        dangling. Losing it is invisible in a diff of a step list.
"""

from __future__ import annotations

import io
import json
import os

import pytest

from custom_components.eufy_vacuum.adapters.dreame import (
    DREAME_MODEL_KEY_REGIMES,
    DREAME_MODEL_REGIMES,
    DREAME_UPKEEP_KEY_GUIDES,
    DREAME_UPKEEP_KEYS,
)
from custom_components.eufy_vacuum.adapters.dreame.maintenance_components import (
    MAINTENANCE_COMPONENTS,
)
from custom_components.eufy_vacuum.adapters.dreame.upkeep_keys import BACK_IN, DOCK_IT

#: The shipped English pack — the real artifact the card bundles, read as the card reads
#: it, not a Python mirror of it. Generated by scripts/sync-dreame-guide-keys.py from the
#: authoring fixture (outside git); this is the only copy inside the repo.
_BUNDLED_EN = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),
    "src", "i18n", "guide-keys.js",
)

#: Panels that exist only when the machine has a base station that washes.
#: `water_tanks` was here until 2026-09-12; the station-tank panel was removed by ruling
#: (Dreame's tank sensors are enums — "just installed or low" — which cannot back a card).
_STATION_ONLY = {"washboard", "mop_pad_holders"}
#: THE MOP IS ONE PANEL. It was four (mop_pad/mop_cloth/mop_roller/mop_track) — a parts
#: inventory read as a card list. Exactly one branch fires, so four names described one job.
_MOP_PANEL = "mop"
#: The clause `tanks` gates: a machine with no station tanks carries its water on board, and on
#: these it rides in the dust bin unit.
_TWO_IN_ONE = "bin.empty_water_too"


def _english_pack() -> dict:
    """The bundled English key pack, parsed out of the generated JS module."""
    src = io.open(_BUNDLED_EN, encoding="utf-8").read()
    return json.loads(src[src.index("{"): src.rindex("}") + 1])


def test_dreame_has_no_brand_registrar_row():
    """[DUK-1] the switch is off, and this is the test that notices it being thrown."""
    from custom_components.eufy_vacuum.adapters.brands import BRAND_REGISTRARS

    assert BRAND_REGISTRARS, "no brands registered — this test is anchored wrong"
    brands = {r.brand_id for r in BRAND_REGISTRARS}
    assert "dreame" not in brands, (
        "Dreame has a BRAND_REGISTRARS row. That row IS the release and it is gated on "
        "a released upstream build carrying Tasshack #1707 — our #1742 is closed as a "
        "duplicate and reads green, which it is not. If the gate has genuinely cleared, "
        "this test is the thing to delete, deliberately."
    )


def test_every_model_routes_to_a_regime_that_exists():
    """[DUK-2] the routing table and the library are two tables; they can drift."""
    assert DREAME_MODEL_KEY_REGIMES, "no models route anywhere — anchored wrong"
    missing = {m: r for m, r in DREAME_MODEL_KEY_REGIMES.items()
               if r not in DREAME_UPKEEP_KEY_GUIDES}
    assert not missing, (
        f"{len(missing)} model(s) route to a regime the key library does not hold, e.g. "
        f"{sorted(missing.items())[:3]}. Every one is a KeyError the moment the release "
        "switch is thrown."
    )
    assert set(DREAME_MODEL_KEY_REGIMES) == set(DREAME_MODEL_REGIMES), (
        "the derived regime-id map has drifted from the measured regime table"
    )


@pytest.mark.parametrize("regime", sorted(DREAME_UPKEEP_KEY_GUIDES))
def test_every_component_has_steps(regime):
    """[DUK-3] a component with nothing to render is worse than an absent one."""
    guide = DREAME_UPKEEP_KEY_GUIDES[regime]
    assert guide, f"regime {regime!r} documents no components at all"
    for component, body in guide.items():
        assert body.get("steps"), f"{regime}/{component} has no steps"
        for field in ("steps", "notes"):
            value = body.get(field, [])
            assert isinstance(value, list), f"{regime}/{component}.{field} is not a list"
            for entry in value:
                assert isinstance(entry, str) and entry.strip(), (
                    f"{regime}/{component}.{field} carries an empty entry"
                )


def test_every_emitted_component_can_reach_a_card():
    """[DUK-4] the manager iterates maintenance_components, NOT the guide library.

    A guide keyed on a component with no row there is authored, translated, shipped and
    invisible — and it looks entirely healthy from inside the guide library, which is how
    it happened: the emitter called a panel ``dust_bin_and_filter`` while the card's
    component was ``filter``.
    """
    emitted = {c for guide in DREAME_UPKEEP_KEY_GUIDES.values() for c in guide}
    orphans = sorted(emitted - set(MAINTENANCE_COMPONENTS))
    assert not orphans, (
        f"{orphans} have key guides but no maintenance_components row, so nothing renders "
        "them. Either add the row, or name the panel after the canonical component the "
        "card already shows."
    )


def test_every_declared_component_is_reachable():
    """[DUK-5] the same join from the other side — a row nothing can fill."""
    emitted = {c for guide in DREAME_UPKEEP_KEY_GUIDES.values() for c in guide}
    dead = sorted(
        c for c, meta in MAINTENANCE_COMPONENTS.items()
        if c not in emitted and not meta.get("sensor_suffix")
    )
    assert not dead, (
        f"{dead} are declared as guide-only cleanables but appear in no regime, so the "
        "gate hides them on every model. A row nothing can fill is a card that can never "
        "say anything."
    )


@pytest.mark.parametrize("regime", sorted(DREAME_UPKEEP_KEY_GUIDES))
def test_the_regime_gates_hardware(regime):
    """[DUK-6] silence beats confident instructions about a part that is not there."""
    mop_type, dock_tier, tanks = regime.split("|")
    components = set(DREAME_UPKEEP_KEY_GUIDES[regime])

    if dock_tier in ("charge_only", "auto_empty"):
        assert not (components & _STATION_ONLY), (
            f"{regime} has no washing station, but documents "
            f"{sorted(components & _STATION_ONLY)}"
        )
    else:
        # THE TRAY IS THE WHOLE STATION SURFACE NOW. The station water tanks lost their panel by
        # ruling (enum sensors cannot back a card, and 6 of the 9 tank keys were pure narration),
        # so a washing station documents the board and nothing else.
        assert "washboard" in components, (
            f"{regime} washes at the station but documents no tray"
        )

    assert "mop_pad_holders" in components or dock_tier != "wash+empty+swap", (
        f"{regime} swaps mop pads at the dock but has no holder panel"
    )

    # EVERY machine that mops gets exactly ONE mop panel, whatever the assembly.
    assert _MOP_PANEL in components, f"{regime} is a {mop_type} machine with no mop panel"
    assert not any(c.startswith("mop_") and c != "mop_pad_holders" for c in components), (
        f"{regime} has a per-assembly mop panel: {sorted(c for c in components if c.startswith('mop_'))}. "
        "The mop is ONE job; which assembly it is belongs in the steps, not in a second card."
    )

    # `tanks` GATES THE 2-IN-1 CLAUSE — the third field's bite, and the only thing it gates now
    # that the station-tank panel is gone. Chris's rule, zero violations over 713 rows: a machine
    # that MOPS and has NO STATION TANKS must carry its water on board, and on these it rides in
    # the dust bin unit. 149 models were handed a bin card that never said to empty it.
    filter_steps = DREAME_UPKEEP_KEY_GUIDES[regime]["filter"]["steps"]
    if tanks == "no" and mop_type != "none":
        assert _TWO_IN_ONE in filter_steps, (
            f"{regime} has no station tanks, so its water is on board in the bin unit — "
            f"but the filter card never says to empty it"
        )
    else:
        assert _TWO_IN_ONE not in filter_steps, (
            f"{regime} keeps its water at the station, but its bin card tells the reader to "
            f"empty water out of it"
        )


def test_every_emitted_key_is_in_the_shipped_english_pack():
    """[DUK-7] a key the pack lacks renders as its own name on the card.

    That fallback is deliberate and deliberately loud, but it must never be reached. The
    sync script refuses to publish a pack that misses one; this catches the other order —
    a key renamed in the emitter and the script never re-run.
    """
    pack = _english_pack()
    missing = sorted(set(DREAME_UPKEEP_KEYS) - set(pack))
    assert not missing, (
        f"{missing} can be emitted but are not in src/i18n/guide-keys.js, so they would "
        "render as bare key names. Re-run scripts/sync-dreame-guide-keys.py."
    )
    unused = sorted(set(pack) - set(DREAME_UPKEEP_KEYS))
    assert not unused, (
        f"{unused} are shipped in every language pack and nothing emits them — either a "
        "step was dropped from the emitter, or 18 packs are carrying dead weight."
    )


def test_a_vacuum_only_machine_is_never_told_to_empty_water():
    """[DUK-6b] the 2-in-1 clause needs BOTH halves of the rule, and Dreame cannot prove it.

    Chris's rule is "if not auto wash BUT MOP YES it has a tank of some kind onboard". A machine
    that does not mop has no water ANYWHERE, so `tanks == "no"` alone is the wrong condition.

    ⛔ THIS TEST CALLS `emit()` DIRECTLY INSTEAD OF WALKING THE SHIPPED REGIMES, AND THAT IS THE
    WHOLE POINT. All 700 Dreame models mop, so no shipped regime has `mop_type="none"` and DUK-6
    — which iterates DREAME_UPKEEP_KEY_GUIDES — can never exercise the branch. The emitter shipped
    with the mop half missing and every Dreame test stayed green. PORTING EUFY FOUND IT: its X8,
    L60 and L60 SES are vacuum-only and were being told to pour water out of a dust bin that has
    never held any.

    A GUARD WITH NO DATA TO BITE ON IS NOT A GUARD. The `none` value entered the catalog with
    Eufy; this test carries the case Dreame's own rows cannot.
    """
    from custom_components.eufy_vacuum.adapters.dreame.upkeep_keys import BIN_IS_2IN1, emit

    for dock in ("charge_only", "auto_empty"):
        steps = {c: s for c, s, _n in emit("none", dock, "no")}["filter"]
        assert BIN_IS_2IN1 not in steps, (
            f"none|{dock}|no does not mop, so it carries no water at all — but its bin card "
            f"says to empty some"
        )
        assert not any(c.startswith("mop") for c, _s, _n in emit("none", dock, "no")), (
            f"none|{dock}|no documents a mop panel on a machine that does not mop"
        )

    # ...and the clause MUST still fire where the machine does mop with no station.
    for mop in ("cloth", "pad", "SimuMop"):
        steps = {c: s for c, s, _n in emit(mop, "charge_only", "no")}["filter"]
        assert BIN_IS_2IN1 in steps, (
            f"{mop}|charge_only|no mops with no station tanks, so its water is on board in the "
            f"bin unit — the clause must fire"
        )


@pytest.mark.parametrize("regime", sorted(DREAME_UPKEEP_KEY_GUIDES))
def test_every_panel_points_at_the_manual(regime):
    """[DUK-6c] the universal note is on EVERY panel, and it is the LAST note.

    These cards are seven jobs distilled from vendor procedures — deliberately not the manual.
    The note bounds what the card claims to be, so a panel without it is a panel implying it is
    exhaustive. It is appended in `emit()` rather than written into each component precisely so
    a NEW component cannot quietly ship without it; this test is what makes that claim bite.

    LAST, not first: the other notes name a consequence the reader cannot see coming. The
    pointer is the least urgent thing on the card and must not displace them.
    """
    from custom_components.eufy_vacuum.adapters.dreame.upkeep_keys import MANUAL

    for component, body in DREAME_UPKEEP_KEY_GUIDES[regime].items():
        notes = body["notes"]
        assert MANUAL in notes, (
            f"{regime}/{component} does not point at the manual — the panel reads as the whole "
            f"procedure when it is one distilled job"
        )
        assert notes[-1] == MANUAL, (
            f"{regime}/{component} has {notes[-1]!r} after the manual pointer; the pointer is "
            f"the least urgent note and goes last"
        )
        assert notes.count(MANUAL) == 1, f"{regime}/{component} points at the manual twice"


def test_the_collapse_holds():
    """[DUK-8] 700 models, 15 regimes, 7 cards — the argument for the whole system."""
    bodies = {
        json.dumps(DREAME_UPKEEP_KEY_GUIDES[r], sort_keys=True)
        for r in DREAME_MODEL_KEY_REGIMES.values()
    }
    assert len(DREAME_MODEL_KEY_REGIMES) == 700, (
        f"{len(DREAME_MODEL_KEY_REGIMES)} models routed, expected 700 — update this "
        "deliberately if the catalog grew"
    )
    assert len(DREAME_UPKEEP_KEY_GUIDES) == 15, (
        f"{len(DREAME_UPKEEP_KEY_GUIDES)} regimes, expected 15"
    )
    assert len(bodies) == 7, (
        f"{len(bodies)} distinct card SETS, expected 7. NOTE THE UNIT: this counts unique "
        "whole-card-SETS, not panels — two regimes that serialise identically collapse to one "
        "entry, so this number moves for reasons that are not decay. It went 7 -> 10 when the "
        "plumbed gate correctly stopped three regimes being carbon copies of their tanked twins, "
        "then 10 -> 7 when the component surface shrank 14 -> 8. Same number, different seven. "
        "A RISE can be two regimes correctly separating; a FALL can be a real merge OR a panel "
        "being retired on purpose. Change it deliberately and say which it was."
    )
    assert len(DREAME_UPKEEP_KEYS) == 42, (
        f"{len(DREAME_UPKEEP_KEYS)} keys, expected 42 — a new key needs authoring in all "
        "18 packs before it can ship"
    )


@pytest.mark.parametrize("regime", sorted(DREAME_UPKEEP_KEY_GUIDES))
def test_every_panel_ends_on_a_closer(regime):
    """[DUK-9] the step that says the task is finished, on every card by design."""
    for component, body in DREAME_UPKEEP_KEY_GUIDES[regime].items():
        steps = body["steps"]
        assert steps[-1] in (DOCK_IT, BACK_IN), (
            f"{regime}/{component} ends on {steps[-1]!r}, not a closer. Every panel closes "
            "with the robot back in service; losing it is invisible in a step-list diff."
        )
        assert sum(s in (DOCK_IT, BACK_IN) for s in steps) == 1, (
            f"{regime}/{component} carries more than one closer"
        )
